# Data Import & Cleaning

### Contents:

- [Data Import](#Data-Import)
- [Data Cleaning](#Data-Cleaning)
- [Feature Engineering](#Feature-Engineering])

### Import Libraries

In [1]:
#import standard libraries
import pandas as pd
import numpy as np

from natsort import natsorted, index_natsorted, order_by_index

#import emoji
import emoji

#import warnings to ignore flags when the project is complete
#import warnings
#warnings.filterwarnings('ignore')

#import pre-processing libraries for data cleaning
import string
import re
import nltk
from nltk.tokenize import RegexpTokenizer, sent_tokenize, word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.sentiment.vader import SentimentIntensityAnalyzer

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

## Data Import

**Read scrapped data for the following videos**

In [2]:
va = pd.read_csv('../../data/scrapped_data/va_OCEANSTARLIVE_263473255843186.csv')

In [3]:
va

video_for  totalEmojiReaction  views
0  OCEANSTARLIVE/videos/263473255843186                  18    608

In [4]:
df = pd.read_csv('../../data/scrapped_data/OCEANSTARLIVE_263473255843186.csv', encoding='utf-8')

In [5]:
df

postComment  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Gd mrg to u miko   
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Oss   
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Oss mrg   
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Lns   
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

In [6]:
#https://stackoverflow.com/questions/32072076/find-the-unique-values-in-a-column-and-then-sort-them
#check if the seller uses multiple accounts to reply
postCommentAuthor_unique = df['postCommentAuthor'].unique()
print(sorted(postCommentAuthor_unique))

['Anna Yong', 'Catherine Gan-Chua', 'Catherine Phua', 'Cindy Lau', 'Clarice Goh', 'Del Del', 'Doris Pay', 'Elizabeth De Cruz', 'Eve Kang', 'Fabian Low', 'Hee Kee Yin', 'Ja Ja', 'Jack Daniel', 'Jacqueline Hoe', 'Jennie Gan', 'Joanne Chong', 'Khym Hoon Sung', 'Nelly Koh', 'OceanStar Seafood', 'Patrick Ong', 'Samuel Goh', 'Teddy Teddy', 'Winnie Wu', 'Ying Yu', 'Yvonne Pang', 'き リーサン', '웬디']


In [7]:
#find comments posted by the seller only
df.loc[df['postCommentAuthor'] == 'OceanStar Seafood']

postComment  \
6                                                                                                                                                                                             So sorry, sold out le   
7                                                                                             2 X KUNNING 500G/ PKT @$11.90</div><div dir="auto" style="text-align: start;">Comment「KN119+1」below to join the Sale.   
11                                                                               2 X BABY CHINESE POMFRET 450G+-/ PKT @$11.11</div><div dir="auto" style="text-align: start;">Comment「BCP+1」below to join the Sale.   
13                                                                                       3 X IQF CHICKEN CUBE 300G /PKT@ $9.90</div><div dir="auto" style="text-align: start;">Comment「CTM+1」below to join the Sale   
14                                                                                       3 X IQF PRIME RIBS 500G+- / P @ $21.90</div><div dir="auto" style="text-align: start;">Comment「PR+1」below to join the Sale   
15                                                                                   2 X IQF CHICKEN MID JOINT 450G+-/ P@ $9.90</div><div dir="auto" style="text-align: start;">Comment「MJ+1」below to join the Sale   
16                                                                                   2 X KASU RABBIT FISH 500G+-/PKT @ $18.00</div><div dir="auto" style="text-align: start;">Comment「RB18+1」below to join the Sale   
19                                                                               2 X BABY CHINESE POMFRET 450G+-/ PKT @$11.11</div><div dir="auto" style="text-align: start;">Comment「BCP+1」below to join the Sale.   
20                                                                               2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90</div><div dir="auto" style="text-align: start;">Comment「WGF+1」below to join the Sale   
22                                                                                       MACKEREL WHOLE 500-600G/ PCS @$9.90</div><div dir="auto" style="text-align: start;">Comment「MAC99+1」below to join the Sale   
23                                                                             WILD GROUPER TAIL PORTION 600-700G/ PCS @$18.00</div><div dir="auto" style="text-align: start;">Comment「WGT+1」below to join the Sale   
24                                                                                   WILD GROUPER HEAD 1.0-1.3 KG/ PCS @$12.90</div><div dir="auto" style="text-align: start;">Comment「WGH+1」below to join the Sale   
28                  BIG FISHES!!!</div><div dir="auto" style="text-align: start;">WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90</div><div dir="auto" style="text-align: start;">Comment「EMP399+1」below to join the Sale   
30                                                                                      3 X FLOWER GROUPER 250-350G/ PCS @$9.90</div><div dir="auto" style="text-align: start;">Comment「FG+1」below to join the Sale   
31                                                                                   WILD GROUPER HEAD 1.0-1.3 KG/ PCS @$12.90</div><div dir="auto" style="text-align: start;">Comment「WGH+1」below to join the Sale   
32                                                                               2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90</div><div dir="auto" style="text-align: start;">Comment「WGF+1」below to join the Sale   
33                                                                                 2 X BABY LEATHER JACKET 450G+-/ PKT @$15.90</div><div dir="auto" style="text-align: start;">Comment「BLJ+1」below to join the Sale   
34                    LAST 4 SET!!!</div><div dir="auto" style="text-align: start;">2 X WILD BARRAMUNDI 450-600G/ PCS @$11.11</div><div dir="auto" style="text-align: start;">Comment「WB11+1」below to join the Sale   
35                                                                              3 X SALMON TROUT FILLET 300-350G/ P

In [8]:
#check the comments to have a gauge
postComment_unique = df['postComment'].unique()
print(sorted(postComment_unique))

[' CHINESE POMFRET 1.9KG/ PCS @$108.00</div><div dir="auto" style="text-align: start;">Comment「CP108+1」below to join the Sale', ' 陈旧旧liao', '1+Buaycai ', '1....', '1kg', '2 X AUTHENTIC THAI MOO PING 5 PCS / PKT @$11.11</div><div dir="auto" style="text-align: start;">Comment「TMP+1」below to join the Sale.', '2 X BABY CHINESE POMFRET 450G+-/ PKT @$11.11</div><div dir="auto" style="text-align: start;">Comment「BCP+1」below to join the Sale.', '2 X BABY LEATHER JACKET 450G+-/ PKT @$15.90</div><div dir="auto" style="text-align: start;">Comment「BLJ+1」below to join the Sale', '2 X BABY WHITE POMFRET 450G+-/ PKT @ $11.11</div><div dir="auto" style="text-align: start;">Comment「BWP+1」below to join the Sale', '2 X BATANG STEAK 250-350G/ PKT @$13.90</div><div dir="auto" style="text-align: start;">Comment「BST+1」below to join the Sale', '2 X BLACK POMFRET 400-500G/ PCS @$15.90</div><div dir="auto" style="text-align: start;">Comment「BP+1」below to join the Sale', '2 X CHINESE POMFRET 250-300G/ PCS @$14.0

## Data Cleaning

### Convert the emojis to text for easy cleaning

We noticed that the emojis have html parsers attached to it. Hence, we will convert the images of the emojis to text first, to remove the html parsers to the emojis, while retaining the emoji's text. We will convert it back to emoji afterwards.

In [9]:
df['postComment'] = df['postComment'].apply(emoji.demojize)

In [10]:
postComment_unique = df['postComment'].unique()
print(sorted(postComment_unique))

[' CHINESE POMFRET 1.9KG/ PCS @$108.00</div><div dir="auto" style="text-align: start;">Comment「CP108+1」below to join the Sale', ' 陈旧旧liao', '1+Buaycai ', '1....', '1kg', '2 X AUTHENTIC THAI MOO PING 5 PCS / PKT @$11.11</div><div dir="auto" style="text-align: start;">Comment「TMP+1」below to join the Sale.', '2 X BABY CHINESE POMFRET 450G+-/ PKT @$11.11</div><div dir="auto" style="text-align: start;">Comment「BCP+1」below to join the Sale.', '2 X BABY LEATHER JACKET 450G+-/ PKT @$15.90</div><div dir="auto" style="text-align: start;">Comment「BLJ+1」below to join the Sale', '2 X BABY WHITE POMFRET 450G+-/ PKT @ $11.11</div><div dir="auto" style="text-align: start;">Comment「BWP+1」below to join the Sale', '2 X BATANG STEAK 250-350G/ PKT @$13.90</div><div dir="auto" style="text-align: start;">Comment「BST+1」below to join the Sale', '2 X BLACK POMFRET 400-500G/ PCS @$15.90</div><div dir="auto" style="text-align: start;">Comment「BP+1」below to join the Sale', '2 X CHINESE POMFRET 250-300G/ PCS @$14.0

### Clean the comments using Regex

From the above unique values of the comments, there are several cleaning issues that needs to be addressed.

    1. Removal of links or URLs. 
        - URLs are present when the Facebook users manually type a link in the comment. 
        - Additionally, when users are tagged, their Facebook profile URL is printed as a result.
        - Similarly, there is a unique URL linked to each emoji as well. 
        
    2. Removal of HTML special entities
        - Examples of HTML special entities are '&amp' and '&gt'. 
        
    3. Removal of other HTML special terms
        - Examples of other HTML special entities are whitespace HTML special entities like '#x200B' and '#xa0'.
        
    4. Removal of HTML Parsers to the Emojis
        - Previously, the emojis have been removed already. However, the HTML parsers to the mojis remain. Hence, they are required to be removed as well.
        
    5. Removal of HTML Parcers to Whitespaces
        - When a next line is entered in the same comment, there will be a HTML parser to the this whitespace. Hence, this are to be removed as well.
        
    6. Removal of HTML Parsers to tagged names
        - When users are tagged in the comments, in addition to their Facebook profile URL, there will be HTML parsers to the tagged names as well. Hence, this are to be removed as well.
        
    7. Removsl of other HTML Parsers   

In [11]:
def clean(row):
               
    # Remove links or URLs
    row['postComment'] = re.sub(
        pattern=r'https?:\/\/.*\.png', 
        repl='', 
        string=row['postComment'],
        flags=re.M)
    
    # Remove HTML special entities (e.g.. &amp, &gt;)
    row['postComment'] = re.sub(
        pattern=r'\&\w*;',
        repl='',
        string=row['postComment'])

    # Remove emoji html parsers
    #https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454
    row['postComment'] = re.sub(
        pattern=r'<img\salt=\"(\:\w*)(\-?)(\w*\:)\"\s[a-z]{6}\=\"\d\d\"\s[a-z]{14}\=.{26}\s[a-z]{3}\=\"\"\s[a-z]{5}\=\"\d\d\"\/>(<\/span>)?',
        repl=r'\1\2\3', 
        string=row['postComment'],
        flags=re.M)
    
    # Remove whitespaces
    row['postComment'] = re.sub(
        pattern=r'<\/div><div\sdir\=\"auto\"\sstyle\=\"text\-align\:\sstart\;\">',
        repl=' ',
        string=row['postComment'],
        flags=re.M)
    
    # Remove emoji html parsers
    row['postComment'] = re.sub(
        pattern = r'<span\sclass\=\"([a-z0-9]{8}\s)+[a-z0-9]{8}\">',
        repl=r' ',
        string=row['postComment'],
        flags=re.M)

    # Remove emoji html parsers
    row['postComment'] = re.sub(
        pattern = r'<div\sclass\=\"([a-z0-9]{8}\s)+[a-z0-9]{8}\".*<\/div>',
        repl=r' ',
        string=row['postComment'],
        flags=re.M)
    
    # Remove emoji html parsers
    row['postComment'] = re.sub(
        pattern=r'<\/span>', 
        repl=' ', 
        string=row['postComment'],
        flags=re.M)
 
    # Remove consecutive non-ASCII characters
    # This will remove the chinese comments
    #https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454
    row['postComment'] = re.sub(
        pattern=r'[^\x00-\x7F]+', 
        repl=' ', 
        string=row['postComment'],
        flags=re.M)

    # Remove links or URLs
    row['postComment'] = re.sub(
        pattern=r'https?:\/\/.*tabindex\=\"\d\"', 
        repl='', 
        string=row['postComment'],
        flags=re.M)
    
    #remove tagged names
    row['postComment'] = re.sub(
        pattern=r'<a class="oajrlxb2 g5ia77u1 qu0x051f esr5mh6w e9989ue4 r7d6kgcz rq0escxv nhd2j8a9 nc684nl6 p7hjln8o kvgmc6g5 cxmmr5t8 oygrvhab hcukyx3x jb3vyjys rz4wbd8a qt6c0cv9 a8nywdso i1ao9s8h esuyzwwr f1sip0of lzcic4wl oo9gr5id gpro0wi8 lrazzd5p" href=">',
        repl='',
        string=row['postComment'],
        flags=re.M)    
    
    #remove tagged names
    row['postComment'] = re.sub(
        pattern=r'<span\sclass\=\"([a-z0-9]{8})\">',
        repl='',
        string=row['postComment'],
        flags=re.M)
    
    #remove tagged names
    row['postComment'] = re.sub(
        pattern=r'<span.*<\/a>',
        repl='',
        string=row['postComment'],
        flags=re.M)
    
    return row

In [12]:
df2 = df.apply(clean, axis=1)

In [13]:
postComment_unique_2 = df2['postComment'].unique()
print(sorted(postComment_unique_2))

[' ', '   ', '    last 25mins', '  !', '  is choose or pick', '  liao', '  same as me  :thinking_face: ', '  wait for me ok not easy to find ', ' :face_screaming_in_fear:  ', ' :grinning_squinting_face: ', ' CHINESE POMFRET 1.9KG/ PCS @$108.00 Comment CP108+1 below to join the Sale', '1+Buaycai ', '1....', '1kg', '2 X AUTHENTIC THAI MOO PING 5 PCS / PKT @$11.11 Comment TMP+1 below to join the Sale.', '2 X BABY CHINESE POMFRET 450G+-/ PKT @$11.11 Comment BCP+1 below to join the Sale.', '2 X BABY LEATHER JACKET 450G+-/ PKT @$15.90 Comment BLJ+1 below to join the Sale', '2 X BABY WHITE POMFRET 450G+-/ PKT @ $11.11 Comment BWP+1 below to join the Sale', '2 X BATANG STEAK 250-350G/ PKT @$13.90 Comment BST+1 below to join the Sale', '2 X BLACK POMFRET 400-500G/ PCS @$15.90 Comment BP+1 below to join the Sale', '2 X CHINESE POMFRET 250-300G/ PCS @$14.00 Comment CP14+1 below to join the Sale', '2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale', '2 X FRA

**Convert encoded emoji text back to emojis**

In [14]:
df2['postComment'] = df2['postComment'].apply(emoji.emojize)

In [15]:
postComment_unique_2 = df2['postComment'].unique()
print(sorted(postComment_unique_2))

[' ', '   ', '    last 25mins', '  !', '  is choose or pick', '  liao', '  same as me  🤔 ', '  wait for me ok not easy to find ', ' CHINESE POMFRET 1.9KG/ PCS @$108.00 Comment CP108+1 below to join the Sale', ' 😆 ', ' 😱  ', '1+Buaycai ', '1....', '1kg', '2 X AUTHENTIC THAI MOO PING 5 PCS / PKT @$11.11 Comment TMP+1 below to join the Sale.', '2 X BABY CHINESE POMFRET 450G+-/ PKT @$11.11 Comment BCP+1 below to join the Sale.', '2 X BABY LEATHER JACKET 450G+-/ PKT @$15.90 Comment BLJ+1 below to join the Sale', '2 X BABY WHITE POMFRET 450G+-/ PKT @ $11.11 Comment BWP+1 below to join the Sale', '2 X BATANG STEAK 250-350G/ PKT @$13.90 Comment BST+1 below to join the Sale', '2 X BLACK POMFRET 400-500G/ PCS @$15.90 Comment BP+1 below to join the Sale', '2 X CHINESE POMFRET 250-300G/ PCS @$14.00 Comment CP14+1 below to join the Sale', '2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale', '2 X FRANCE COD FL 400-500G/ PKT @$59.90 Comment FCF+1 below to join 

### Drop Empty Posts

Blank comments are dropped to ensure that unique comments are obtained.

In [16]:
#drop empty posts
df2 = df2.loc[((df['postComment'] != ' ')
              & (df['postComment'] != '  ')
              & (df['postComment'] != '   ')),:]

In [17]:
postComment_unique_2 = df2['postComment'].unique()
print(sorted(postComment_unique_2))

['    last 25mins', '  !', '  is choose or pick', '  liao', '  same as me  🤔 ', '  wait for me ok not easy to find ', ' CHINESE POMFRET 1.9KG/ PCS @$108.00 Comment CP108+1 below to join the Sale', ' 😆 ', ' 😱  ', '1+Buaycai ', '1....', '1kg', '2 X AUTHENTIC THAI MOO PING 5 PCS / PKT @$11.11 Comment TMP+1 below to join the Sale.', '2 X BABY CHINESE POMFRET 450G+-/ PKT @$11.11 Comment BCP+1 below to join the Sale.', '2 X BABY LEATHER JACKET 450G+-/ PKT @$15.90 Comment BLJ+1 below to join the Sale', '2 X BABY WHITE POMFRET 450G+-/ PKT @ $11.11 Comment BWP+1 below to join the Sale', '2 X BATANG STEAK 250-350G/ PKT @$13.90 Comment BST+1 below to join the Sale', '2 X BLACK POMFRET 400-500G/ PCS @$15.90 Comment BP+1 below to join the Sale', '2 X CHINESE POMFRET 250-300G/ PCS @$14.00 Comment CP14+1 below to join the Sale', '2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale', '2 X FRANCE COD FL 400-500G/ PKT @$59.90 Comment FCF+1 below to join the Sale.', 

### Reindexing the dataframe 
**New Column to reindex the dataframe in accordance to time**

From the data, we can tell that there is an inconsistent timestamp being used in the column 'postCommentTime'. For example, there are times like '0:57' and '1:00:14' which indicates 0 hour 0 mins 57 secs, and 1 hour 0 mins 14 secs. 

Hence, a new column 'postCommentTime_final' is created to ensure that a timestamp of HH:MM:SS is being used consistently throughout. However, we note that the number of days is being included for TimeDeltaIndex.

As a result, we will read the timestamp, by excluding the number of days.  

In [18]:
#TimedeltaIndex
#https://stackoverflow.com/questions/54877467/pandas-convert-hhmm-and-hhmmss-to-standard-hhmmss-in-python
# for example, time of '0:57' will then be 00:00:57; 0 hours 0 mins 57 secs
df2['postCommentTime_final'] = pd.to_timedelta(np.where(df2['postCommentTime'].str.count(':') == 1, '00:' + df2['postCommentTime'], df2['postCommentTime']))

In [19]:
df2.head()

postComment postCommentAuthor postCommentTime postCommentTime_final
0  Gd mrg to u miko         Doris Pay            0:44       0 days 00:00:44
1               Oss          Eve Kang            0:46       0 days 00:00:46
2           Oss mrg        Samuel Goh            0:48       0 days 00:00:48
3               Lns         Doris Pay            0:51       0 days 00:00:51
4              LNS         Jennie Gan            0:55       0 days 00:00:55

In [20]:
df2['postCommentTime_final'] = df2['postCommentTime_final'].astype(str).map(lambda x: x[7:])

In [21]:
df2

postComment  \
0                                                                                                  Gd mrg to u miko   
1                                                                                                               Oss   
2                                                                                                           Oss mrg   
3                                                                                                               Lns   
4                                                                                                              LNS    
5                                                                                                               Oss   
6                                                                                             So sorry, sold out le   
7                                             2 X KUNNING 500G/ PKT @$11.90 Comment KN119+1 below to join the Sale.   
8                                                                                                              PC+2   
9                                                                                                               Thx   
10                                                                                                            TMP+1   
11                               2 X BABY CHINESE POMFRET 450G+-/ PKT @$11.11 Comment BCP+1 below to join the Sale.   
12                                                                                                          KN119+1   
13                                       3 X IQF CHICKEN CUBE 300G /PKT@ $9.90 Comment CTM+1 below to join the Sale   
14                                       3 X IQF PRIME RIBS 500G+- / P @ $21.90 Comment PR+1 below to join the Sale   
15                                   2 X IQF CHICKEN MID JOINT 450G+-/ P@ $9.90 Comment MJ+1 below to join the Sale   
16                                   2 X KASU RABBIT FISH 500G+-/PKT @ $18.00 Comment RB18+1 below to join the Sale   
17                                                                                                            BCP+1   
18                                                                                                        Lunnnnnnn   
19                               2 X BABY CHINESE POMFRET 450G+-/ PKT @$11.11 Comment BCP+1 below to join the Sale.   
20                               2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGF+1 below to join the Sale   
21                                                                                                            Wgf+1   
22                                       MACKEREL WHOLE 500-600G/ PCS @$9.90 Comment MAC99+1 below to join the Sale   
23                             WILD GROUPER TAIL PORTION 600-700G/ PCS @$18.00 Comment WGT+1 below to join the Sale   
24                                   WILD GROUPER HEAD 1.0-1.3 KG/ PCS @$12.90 Comment WGH+1 below to join the Sale   
25                                                                                               morning mc  oss...   
26                                                                       wah the tail so big, can use to big ppl...   
27                                                                                  Good morning miko and OSS team    
28                  BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
29                                                                                                        busy lah.   
30                                      3 X FLOWER GROUPER 250-350G/ PCS @$9.90 Comment FG+1 below to join the Sale   
31                                   WILD GROUPER HEAD 1.0-1.3 KG/ PCS @$12.90 Comment WGH+1 below to join the Sale   
32                               2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGF+1 below to join the Sale   
33                                 2 X BABY LEATHER JACKET

In [22]:
#reindex according to postCommentTime_final
#previous natsort in data collection didnt take into account the different timestamp format
df4 = df2.reindex(index=order_by_index(df2.index, index_natsorted(df2.postCommentTime_final)))

In [23]:
df4

postComment  \
0                                                                                                  Gd mrg to u miko   
1                                                                                                               Oss   
2                                                                                                           Oss mrg   
3                                                                                                               Lns   
4                                                                                                              LNS    
5                                                                                                               Oss   
27                                                                                  Good morning miko and OSS team    
28                  BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
63                                                                                                             OSS    
74                                WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
75                                                                                                              Oss   
76                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
77                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
78                                                                                                Good morning OSS    
79                               BALAI THREADFIN WHOL 2.4-2.8KG/ PCS @$78.00 Comment BTW78+1 below to join the Sale   
80                                                                                                         Mrg miko   
81                           BALAI THREADFIN WHOLE 5.5-6.0 KG/ PCS @$168.00 Comment BTW168+1 below to join the Sale   
82                                                                                                Mee siam mee siam   
83                                                                                                             LNS    
84                                                                                                             LNS    
85                                       MACKEREL WHOLE 500-600G/ PCS @$9.90 Comment MAC99+1 below to join the Sale   
86                        2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale   
87                                 SALMON TROUT WHOLE 4.0-4.3 KG/ PCS @$108.00 Comment STW+1 below to join the Sale   
88                                  RED SNAPPER WHOLE 1.7-1.9 KG/ PCS @$33.33 Comment RS33+1 below to join the Sale   
89                               WILD BARRAMUNDI WHOLE 3.5-3.9 KG/ PCS @ $49.90 Comment WB+1 below to join the Sale   
90                                                                                                               LS   
91                                WILD GROUPER WHOLE 2.2-2.6 KG/ PCS @$39.90 Comment WG399+1 below to join the Sale   
92                                 RED GROUPER WHOLE 1.1-1.3KG / PCS @ $35.00 Comment RG35+1 below to join the Sale   
93                                                                                   Good morning Miko and OSS team   
94                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
95                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
96                                                                           Good Morning Miko, OSS Team  Everyone    
97                                                                                                              😱     
98                                                        

In [24]:
#reset the index for the dataframe
#https://stackoverflow.com/questions/20490274/how-to-reset-index-in-a-pandas-dataframe

df4 = df4.reset_index(drop=True)

In [25]:
df4

postComment  \
0                                                                                                  Gd mrg to u miko   
1                                                                                                               Oss   
2                                                                                                           Oss mrg   
3                                                                                                               Lns   
4                                                                                                              LNS    
5                                                                                                               Oss   
6                                                                                   Good morning miko and OSS team    
7                   BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
8                                                                                                              OSS    
9                                 WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
10                                                                                                              Oss   
11                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
12                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
13                                                                                                Good morning OSS    
14                               BALAI THREADFIN WHOL 2.4-2.8KG/ PCS @$78.00 Comment BTW78+1 below to join the Sale   
15                                                                                                         Mrg miko   
16                           BALAI THREADFIN WHOLE 5.5-6.0 KG/ PCS @$168.00 Comment BTW168+1 below to join the Sale   
17                                                                                                Mee siam mee siam   
18                                                                                                             LNS    
19                                                                                                             LNS    
20                                       MACKEREL WHOLE 500-600G/ PCS @$9.90 Comment MAC99+1 below to join the Sale   
21                        2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale   
22                                 SALMON TROUT WHOLE 4.0-4.3 KG/ PCS @$108.00 Comment STW+1 below to join the Sale   
23                                  RED SNAPPER WHOLE 1.7-1.9 KG/ PCS @$33.33 Comment RS33+1 below to join the Sale   
24                               WILD BARRAMUNDI WHOLE 3.5-3.9 KG/ PCS @ $49.90 Comment WB+1 below to join the Sale   
25                                                                                                               LS   
26                                WILD GROUPER WHOLE 2.2-2.6 KG/ PCS @$39.90 Comment WG399+1 below to join the Sale   
27                                 RED GROUPER WHOLE 1.1-1.3KG / PCS @ $35.00 Comment RG35+1 below to join the Sale   
28                                                                                   Good morning Miko and OSS team   
29                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
30                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
31                                                                           Good Morning Miko, OSS Team  Everyone    
32                                                                                                              😱     
33                                                        

**Obtain the length of the video**

Assuming that the last comment of the video is the total length of the video, we will input the length of the video from the comments dataframe into the video attributes dataframe.

In [26]:
#retrieve last comment to obtain the length of the video
df4['postCommentTime_final'].iloc[-1]

'01:18:21'

In [27]:
#https://stackoverflow.com/questions/6402812/how-to-convert-an-hmmss-time-string-to-seconds-in-python
def get_sec(time_str):
    """Get Seconds from time."""
    h, m, s = time_str.split(':')
    return int(h) * 3600 + int(m) * 60 + int(s)

In [28]:
#retrieve last comment to obtain the length of the video in seconds
va['videoLength']= get_sec(df4['postCommentTime_final'].iloc[-1])

In [29]:
va

video_for  totalEmojiReaction  views  \
0  OCEANSTARLIVE/videos/263473255843186                  18    608   

   videoLength  
0         4701

## Feature Engineering

### Comments made by the Seller

**New Column to identify the number of comments made by the seller in the video**

From the total sum of comments made by the seller, we will input it into the video attributes dataframe.

In [30]:
(df4['postCommentAuthor']=='OceanStar Seafood').sum()

131

In [31]:
va['numSellerComments'] = (df4['postCommentAuthor']=='OceanStar Seafood').sum()

In [32]:
va

video_for  totalEmojiReaction  views  \
0  OCEANSTARLIVE/videos/263473255843186                  18    608   

   videoLength  numSellerComments  
0         4701                131

**New Column to identify if the comment is made by the Seller or not**

In [33]:
#create a new column to show if the comment is made by the seller or not
#1 for customers, 0 for seller
#to delete column 'notSeller' in due course, as it is solely used for to find out the quantity of sales being made.
df4['notSeller'] = df4['postCommentAuthor'].map(lambda x:1 if x !='OceanStar Seafood' else 0)

In [34]:
df4['isSeller'] = df4['postCommentAuthor'].map(lambda x:1 if x =='OceanStar Seafood' else 0)

In [35]:
df4.head()

postComment postCommentAuthor postCommentTime postCommentTime_final  \
0  Gd mrg to u miko         Doris Pay            0:44              00:00:44   
1               Oss          Eve Kang            0:46              00:00:46   
2           Oss mrg        Samuel Goh            0:48              00:00:48   
3               Lns         Doris Pay            0:51              00:00:51   
4              LNS         Jennie Gan            0:55              00:00:55   

   notSeller  isSeller  
0          1         0  
1          1         0  
2          1         0  
3          1         0  
4          1         0

In [36]:
df4['isSeller'].value_counts()

0    148
1    131
Name: isSeller, dtype: int64

In [37]:
#show all the seller's comments
df4.loc[df4['isSeller'] == 1]

postComment  \
7                   BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
9                                 WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
11                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
12                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
14                               BALAI THREADFIN WHOL 2.4-2.8KG/ PCS @$78.00 Comment BTW78+1 below to join the Sale   
16                           BALAI THREADFIN WHOLE 5.5-6.0 KG/ PCS @$168.00 Comment BTW168+1 below to join the Sale   
20                                       MACKEREL WHOLE 500-600G/ PCS @$9.90 Comment MAC99+1 below to join the Sale   
21                        2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale   
22                                 SALMON TROUT WHOLE 4.0-4.3 KG/ PCS @$108.00 Comment STW+1 below to join the Sale   
23                                  RED SNAPPER WHOLE 1.7-1.9 KG/ PCS @$33.33 Comment RS33+1 below to join the Sale   
24                               WILD BARRAMUNDI WHOLE 3.5-3.9 KG/ PCS @ $49.90 Comment WB+1 below to join the Sale   
26                                WILD GROUPER WHOLE 2.2-2.6 KG/ PCS @$39.90 Comment WG399+1 below to join the Sale   
27                                 RED GROUPER WHOLE 1.1-1.3KG / PCS @ $35.00 Comment RG35+1 below to join the Sale   
29                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
30                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
41            CHINESE POMFRET SERIES!!!  CHINESE POMFRET 1.9KG/ PCS @$108.00 Comment CP108+1 below to join the Sale   
42            CHINESE POMFRET SERIES!!!  CHINESE POMFRET 1.9KG/ PCS @$108.00 Comment CP108+1 below to join the Sale   
45                         ONLY 1 PC!!!  CHINESE POMFRET 1.9KG/ PCS @$108.00 Comment CP108+1 below to join the Sale   
46                             LAST PCS!!! CHINESE POMFRET 1.8KG/ PCS @$99.00 Comment CP99+1 below to join the Sale   
49                             LAST PCS!!! CHINESE POMFRET 1.6KG/ PCS @$88.00 Comment CP88+1 below to join the Sale   
52                          LAST 2 PCS!!!! CHINESE POMFRET 1.4KG/ PCS @$77.00 Comment CP77+1 below to join the Sale   
53                                    CHINESE POMFRET 500-600G/ PCS @$22.00   Comment CP22+1 below to join the Sale   
54                                  2 X CHINESE POMFRET 250-300G/ PCS @$14.00 Comment CP14+1 below to join the Sale   
56                                          2 X SMALL SQUID 500G/ PKT @$19.90 Comment SLD+1 below to join the Sale.   
57                                    3 X BATANG SOUP SLICED 300G/ PKT @$24.00 Comment BSS+1 below to join the Sale   
58                               2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGH+1 below to join the Sale   
61                                2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGF1 below to join the Sale   
62                               2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGF+1 below to join the Sale   
65                         CHOCO JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment CCL+1 below to join the Sale.   
66                         CHOCO JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment CCL+1 below to join the Sale.   
68                    STRAWBERRY JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment SBY+1 below to join the Sale.   
69                        VANILA JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment VNL+1 below to join the Sale.   
70                        MATCHA JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment MCA+1 below to join the Sale.   
75                         CHOCO JAPAN HOKKAIDO CREPE CAKE

### Length of comments

**New Column to identify the length of each comment**

From the comments, we take the length of each comment as the total number of words each comment has.

In [38]:
#length of each comment
#https://stackoverflow.com/questions/37483470/how-to-calculate-number-of-words-in-a-string-in-dataframe
df4['postCommentLength'] = df4['postComment'].str.split().str.len()

In [39]:
df4.head(10)

postComment  \
0                                                                                 Gd mrg to u miko   
1                                                                                              Oss   
2                                                                                          Oss mrg   
3                                                                                              Lns   
4                                                                                             LNS    
5                                                                                              Oss   
6                                                                  Good morning miko and OSS team    
7  BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
8                                                                                             OSS    
9                WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   

   postCommentAuthor postCommentTime postCommentTime_final  notSeller  \
0          Doris Pay            0:44              00:00:44          1   
1           Eve Kang            0:46              00:00:46          1   
2         Samuel Goh            0:48              00:00:48          1   
3          Doris Pay            0:51              00:00:51          1   
4         Jennie Gan            0:55              00:00:55          1   
5          Doris Pay            0:58              00:00:58          1   
6         Jennie Gan            1:07              00:01:07          1   
7  OceanStar Seafood            1:07              00:01:07          0   
8         Jennie Gan            1:16              00:01:16          1   
9  OceanStar Seafood            1:32              00:01:32          0   

   isSeller  postCommentLength  
0         0                  5  
1         0                  1  
2         0                  2  
3         0                  1  
4         0                  1  
5         0                  1  
6         0                  6  
7         1                 15  
8         0                  1  
9         1                 13

**New Column to identify the total number of comments in the video**

From the total number of comments in the video, we will input it into the video attributes dataframe.

In [40]:
#total number of comments
df4['postCommentLength'].sum()

2478

In [41]:
va['numComments'] = df4['postCommentLength'].sum()

In [42]:
va

video_for  totalEmojiReaction  views  \
0  OCEANSTARLIVE/videos/263473255843186                  18    608   

   videoLength  numSellerComments  numComments  
0         4701                131         2478

### LNS

LNS is an acronym that stands for 'like and share'. It is a form of customer engagement as it indicates by the customers to the sellers that they have liked and shared the video on their Facebook wall. 

**New Column to identify if Customers are engaging in liking and sharing the video**

In [43]:
#if the customer has commented 'lns' which stands for 'like & shared'
def lns(comment):
    if re.search(r'(l)(n?)(s)', comment, re.IGNORECASE):
        return int(1)
    else:
        return int(0)

In [44]:
df4['lns'] = df4['postComment'].map(lambda x:lns(x))

In [45]:
df4.head()

postComment postCommentAuthor postCommentTime postCommentTime_final  \
0  Gd mrg to u miko         Doris Pay            0:44              00:00:44   
1               Oss          Eve Kang            0:46              00:00:46   
2           Oss mrg        Samuel Goh            0:48              00:00:48   
3               Lns         Doris Pay            0:51              00:00:51   
4              LNS         Jennie Gan            0:55              00:00:55   

   notSeller  isSeller  postCommentLength  lns  
0          1         0                  5    0  
1          1         0                  1    0  
2          1         0                  2    0  
3          1         0                  1    1  
4          1         0                  1    1

**New Column to identify if the number of Customers who explicitly inform the sellers that they are engaging in liking and sharing the video**

In [46]:
#range of customer's engagement for LNS
df4['lns'].value_counts()

0    267
1     12
Name: lns, dtype: int64

In [47]:
(df4['lns']==1).sum()

12

In [48]:
va['lnsQuantity'] = (df4['lns']==1).sum()

In [49]:
va

video_for  totalEmojiReaction  views  \
0  OCEANSTARLIVE/videos/263473255843186                  18    608   

   videoLength  numSellerComments  numComments  lnsQuantity  
0         4701                131         2478           12

## Sales Quantity

**New Columns to identify the quantity of sales made**

From the comments, using regex, we first see an overview of the comments that are related to the sale of the products. 

In [50]:
df4[df4['postComment'].str.contains('(\w*\+\d)', regex=True)]

/var/folders/yf/6dz2fhvj1wl4h0563j2qw8hh0000gn/T/ipykernel_52953/2000505306.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  df4[df4['postComment'].str.contains('(\w*\+\d)', regex=True)]


postComment  \
7                   BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
9                                 WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
11                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
12                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
14                               BALAI THREADFIN WHOL 2.4-2.8KG/ PCS @$78.00 Comment BTW78+1 below to join the Sale   
16                           BALAI THREADFIN WHOLE 5.5-6.0 KG/ PCS @$168.00 Comment BTW168+1 below to join the Sale   
20                                       MACKEREL WHOLE 500-600G/ PCS @$9.90 Comment MAC99+1 below to join the Sale   
21                        2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale   
22                                 SALMON TROUT WHOLE 4.0-4.3 KG/ PCS @$108.00 Comment STW+1 below to join the Sale   
23                                  RED SNAPPER WHOLE 1.7-1.9 KG/ PCS @$33.33 Comment RS33+1 below to join the Sale   
24                               WILD BARRAMUNDI WHOLE 3.5-3.9 KG/ PCS @ $49.90 Comment WB+1 below to join the Sale   
26                                WILD GROUPER WHOLE 2.2-2.6 KG/ PCS @$39.90 Comment WG399+1 below to join the Sale   
27                                 RED GROUPER WHOLE 1.1-1.3KG / PCS @ $35.00 Comment RG35+1 below to join the Sale   
29                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
30                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
41            CHINESE POMFRET SERIES!!!  CHINESE POMFRET 1.9KG/ PCS @$108.00 Comment CP108+1 below to join the Sale   
42            CHINESE POMFRET SERIES!!!  CHINESE POMFRET 1.9KG/ PCS @$108.00 Comment CP108+1 below to join the Sale   
45                         ONLY 1 PC!!!  CHINESE POMFRET 1.9KG/ PCS @$108.00 Comment CP108+1 below to join the Sale   
46                             LAST PCS!!! CHINESE POMFRET 1.8KG/ PCS @$99.00 Comment CP99+1 below to join the Sale   
49                             LAST PCS!!! CHINESE POMFRET 1.6KG/ PCS @$88.00 Comment CP88+1 below to join the Sale   
52                          LAST 2 PCS!!!! CHINESE POMFRET 1.4KG/ PCS @$77.00 Comment CP77+1 below to join the Sale   
53                                    CHINESE POMFRET 500-600G/ PCS @$22.00   Comment CP22+1 below to join the Sale   
54                                  2 X CHINESE POMFRET 250-300G/ PCS @$14.00 Comment CP14+1 below to join the Sale   
56                                          2 X SMALL SQUID 500G/ PKT @$19.90 Comment SLD+1 below to join the Sale.   
57                                    3 X BATANG SOUP SLICED 300G/ PKT @$24.00 Comment BSS+1 below to join the Sale   
58                               2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGH+1 below to join the Sale   
60                                                                                                            Wgh+1   
62                               2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGF+1 below to join the Sale   
65                         CHOCO JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment CCL+1 below to join the Sale.   
66                         CHOCO JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment CCL+1 below to join the Sale.   
68                    STRAWBERRY JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment SBY+1 below to join the Sale.   
69                        VANILA JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment VNL+1 below to join the Sale.   
70                        MATCHA JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment MCA+1 below to join the Sale.   
72                                                        

In [51]:
def sale(comment):
    if re.search(r'(\w*\+)(\d)', comment):
        return int(re.search(r'\w*\+\d', comment).group(0)[-1])
    else:
        return int(0)

In [52]:
df4['sales'] = df4['postComment'].apply(lambda x:sale(x))

In [53]:
df4.head(10)

postComment  \
0                                                                                 Gd mrg to u miko   
1                                                                                              Oss   
2                                                                                          Oss mrg   
3                                                                                              Lns   
4                                                                                             LNS    
5                                                                                              Oss   
6                                                                  Good morning miko and OSS team    
7  BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
8                                                                                             OSS    
9                WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   

   postCommentAuthor postCommentTime postCommentTime_final  notSeller  \
0          Doris Pay            0:44              00:00:44          1   
1           Eve Kang            0:46              00:00:46          1   
2         Samuel Goh            0:48              00:00:48          1   
3          Doris Pay            0:51              00:00:51          1   
4         Jennie Gan            0:55              00:00:55          1   
5          Doris Pay            0:58              00:00:58          1   
6         Jennie Gan            1:07              00:01:07          1   
7  OceanStar Seafood            1:07              00:01:07          0   
8         Jennie Gan            1:16              00:01:16          1   
9  OceanStar Seafood            1:32              00:01:32          0   

   isSeller  postCommentLength  lns  sales  
0         0                  5    0      0  
1         0                  1    0      0  
2         0                  2    0      0  
3         0                  1    1      0  
4         0                  1    1      0  
5         0                  1    0      0  
6         0                  6    0      0  
7         1                 15    0      1  
8         0                  1    0      0  
9         1                 13    0      1

In [54]:
#sales made by the customers; exclude the seller's comments on the codes for the sales
#https://stackoverflow.com/questions/19914937/applying-function-with-multiple-arguments-to-create-a-new-pandas-column
df4['salesQuantity'] = np.multiply(df4['notSeller'], df4['sales'])

In [55]:
df4.head(10)

postComment  \
0                                                                                 Gd mrg to u miko   
1                                                                                              Oss   
2                                                                                          Oss mrg   
3                                                                                              Lns   
4                                                                                             LNS    
5                                                                                              Oss   
6                                                                  Good morning miko and OSS team    
7  BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
8                                                                                             OSS    
9                WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   

   postCommentAuthor postCommentTime postCommentTime_final  notSeller  \
0          Doris Pay            0:44              00:00:44          1   
1           Eve Kang            0:46              00:00:46          1   
2         Samuel Goh            0:48              00:00:48          1   
3          Doris Pay            0:51              00:00:51          1   
4         Jennie Gan            0:55              00:00:55          1   
5          Doris Pay            0:58              00:00:58          1   
6         Jennie Gan            1:07              00:01:07          1   
7  OceanStar Seafood            1:07              00:01:07          0   
8         Jennie Gan            1:16              00:01:16          1   
9  OceanStar Seafood            1:32              00:01:32          0   

   isSeller  postCommentLength  lns  sales  salesQuantity  
0         0                  5    0      0              0  
1         0                  1    0      0              0  
2         0                  2    0      0              0  
3         0                  1    1      0              0  
4         0                  1    1      0              0  
5         0                  1    0      0              0  
6         0                  6    0      0              0  
7         1                 15    0      1              0  
8         0                  1    0      0              0  
9         1                 13    0      1              0

In [56]:
#range of sales quantity
df4['salesQuantity'].value_counts()

0    255
1     19
2      5
Name: salesQuantity, dtype: int64

In [57]:
#total number of orders made
df4['salesQuantity'].sum()

29

In [58]:
va['salesQuantity'] = df4['salesQuantity'].sum()

In [59]:
va

video_for  totalEmojiReaction  views  \
0  OCEANSTARLIVE/videos/263473255843186                  18    608   

   videoLength  numSellerComments  numComments  lnsQuantity  salesQuantity  
0         4701                131         2478           12             29

## Products 

The seller will comment and post the unique product codes for each product. Thereafter, customers who are keen on purchasing the products will explicitly comment out the specific & unique product codes, in addition to the quanityt of each product that they wish to purchase.

**New Columns to identify the products purchased by the Customers**

Regex is used to identify the products being offered and the products being purchased as well.

In [60]:
#function to identify the code of the product bought
def sale2(comment):
    if re.search(r'[a-zA-Z]*\s?(\d*)?\s?\+\s?\d', comment):
        return str(re.search(r'[a-zA-Z]*\s?(\d*)?\s?\+\s?\d', comment).group(0)[:-2])
    else:
        return int(0)

In [61]:
#identifies all comments that have the codes of the products, including the seller's comments.
#this column will be dropped afterwards.
df4['product'] = df4['postComment'].apply(lambda x:sale2(x))

Since the column 'notSeller' returns a value of 1 if it is written by a customer, and a value of 0 if it is written by the seller instead, multiplying by the column 'product' will result in a positive value for product codes written by the customers only.

This is because the regex product codes are written by both the sellers and the customers - by the seller to advice on the product details and the corresponding codes, and by the customers if they wish to purchase the specific products.

In [62]:
#products bought by Customers; exclude the seller's comments on the product details 
df4['productBought'] = np.multiply(df4['notSeller'], df4['product'])

In [63]:
df4['productBought'].unique()

array([0, '', 'Wgh', 'VNL', 'MCA', 'BSS', 'WGF', 'Res199', 'WST299', 'SP',
       'Wst299', 'Rg35', 'Tms', 'Amb', 'Bsd', 'Bss', 'Otak', 'Bop', 'BWP',
       'OTAK', 'PC', 'TMP', 'KN119', 'BCP', 'Wgf', 'WGT'], dtype=object)

In [64]:
#https://stackoverflow.com/questions/13445241/replacing-blank-values-white-space-with-nan-in-pandas
df4['productBought'] = df4['productBought'].replace(r'^\s*$', int(0), regex=True)

In [65]:
df4['productBought'].unique()

array([0, 'Wgh', 'VNL', 'MCA', 'BSS', 'WGF', 'Res199', 'WST299', 'SP',
       'Wst299', 'Rg35', 'Tms', 'Amb', 'Bsd', 'Bss', 'Otak', 'Bop', 'BWP',
       'OTAK', 'PC', 'TMP', 'KN119', 'BCP', 'Wgf', 'WGT'], dtype=object)

In [66]:
#change the produce codes to be uppercase for consistency, and since python is case sensitive.
#https://stackoverflow.com/questions/39512002/convert-whole-dataframe-from-lower-case-to-upper-case-with-pandas
df4['productBought'] = df4['productBought'].astype(str).str.upper()

In [67]:
df4['productBought'].unique()

array(['0', 'WGH', 'VNL', 'MCA', 'BSS', 'WGF', 'RES199', 'WST299', 'SP',
       'RG35', 'TMS', 'AMB', 'BSD', 'OTAK', 'BOP', 'BWP', 'PC', 'TMP',
       'KN119', 'BCP', 'WGT'], dtype=object)

In [68]:
df4.head()

postComment postCommentAuthor postCommentTime postCommentTime_final  \
0  Gd mrg to u miko         Doris Pay            0:44              00:00:44   
1               Oss          Eve Kang            0:46              00:00:46   
2           Oss mrg        Samuel Goh            0:48              00:00:48   
3               Lns         Doris Pay            0:51              00:00:51   
4              LNS         Jennie Gan            0:55              00:00:55   

   notSeller  isSeller  postCommentLength  lns  sales  salesQuantity product  \
0          1         0                  5    0      0              0       0   
1          1         0                  1    0      0              0       0   
2          1         0                  2    0      0              0       0   
3          1         0                  1    1      0              0       0   
4          1         0                  1    1      0              0       0   

  productBought  
0             0  
1             0  
2             0  
3             0  
4             0

In [69]:
df4.head(50)

postComment  \
0                                                                                        Gd mrg to u miko   
1                                                                                                     Oss   
2                                                                                                 Oss mrg   
3                                                                                                     Lns   
4                                                                                                    LNS    
5                                                                                                     Oss   
6                                                                         Good morning miko and OSS team    
7         BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
8                                                                                                    OSS    
9                       WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
10                                                                                                    Oss   
11              RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
12               RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
13                                                                                      Good morning OSS    
14                     BALAI THREADFIN WHOL 2.4-2.8KG/ PCS @$78.00 Comment BTW78+1 below to join the Sale   
15                                                                                               Mrg miko   
16                 BALAI THREADFIN WHOLE 5.5-6.0 KG/ PCS @$168.00 Comment BTW168+1 below to join the Sale   
17                                                                                      Mee siam mee siam   
18                                                                                                   LNS    
19                                                                                                   LNS    
20                             MACKEREL WHOLE 500-600G/ PCS @$9.90 Comment MAC99+1 below to join the Sale   
21              2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale   
22                       SALMON TROUT WHOLE 4.0-4.3 KG/ PCS @$108.00 Comment STW+1 below to join the Sale   
23                        RED SNAPPER WHOLE 1.7-1.9 KG/ PCS @$33.33 Comment RS33+1 below to join the Sale   
24                     WILD BARRAMUNDI WHOLE 3.5-3.9 KG/ PCS @ $49.90 Comment WB+1 below to join the Sale   
25                                                                                                     LS   
26                      WILD GROUPER WHOLE 2.2-2.6 KG/ PCS @$39.90 Comment WG399+1 below to join the Sale   
27                       RED GROUPER WHOLE 1.1-1.3KG / PCS @ $35.00 Comment RG35+1 below to join the Sale   
28                                                                         Good morning Miko and OSS team   
29              RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
30               RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
31                                                                 Good Morning Miko, OSS Team  Everyone    
32                                                                                                    😱     
33                                                                                  Mrg kelvin n Lena too   
34                                                                           Good morning Miko n Team OSS   
35                                                                                       Today Wednesday    
36                                                           

### Price of Products

**New Column to identify the price of the products**

This new column is created to identify the regex of the unique product codes and their corresponding prices, as adviced by the seller.

In [70]:
def price(comment):
    if re.search(r'(\@)(\$)( ?)(.*)', comment):
        return str(re.search(r'(\$)( ?)(.*)', comment).group(0)[:-23])
    else:
        return int(0)

In [71]:
df4['productPrice'] = df4['postComment'].apply(lambda x:price(x))

In [72]:
df4.head(50)

postComment  \
0                                                                                        Gd mrg to u miko   
1                                                                                                     Oss   
2                                                                                                 Oss mrg   
3                                                                                                     Lns   
4                                                                                                    LNS    
5                                                                                                     Oss   
6                                                                         Good morning miko and OSS team    
7         BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
8                                                                                                    OSS    
9                       WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
10                                                                                                    Oss   
11              RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
12               RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
13                                                                                      Good morning OSS    
14                     BALAI THREADFIN WHOL 2.4-2.8KG/ PCS @$78.00 Comment BTW78+1 below to join the Sale   
15                                                                                               Mrg miko   
16                 BALAI THREADFIN WHOLE 5.5-6.0 KG/ PCS @$168.00 Comment BTW168+1 below to join the Sale   
17                                                                                      Mee siam mee siam   
18                                                                                                   LNS    
19                                                                                                   LNS    
20                             MACKEREL WHOLE 500-600G/ PCS @$9.90 Comment MAC99+1 below to join the Sale   
21              2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale   
22                       SALMON TROUT WHOLE 4.0-4.3 KG/ PCS @$108.00 Comment STW+1 below to join the Sale   
23                        RED SNAPPER WHOLE 1.7-1.9 KG/ PCS @$33.33 Comment RS33+1 below to join the Sale   
24                     WILD BARRAMUNDI WHOLE 3.5-3.9 KG/ PCS @ $49.90 Comment WB+1 below to join the Sale   
25                                                                                                     LS   
26                      WILD GROUPER WHOLE 2.2-2.6 KG/ PCS @$39.90 Comment WG399+1 below to join the Sale   
27                       RED GROUPER WHOLE 1.1-1.3KG / PCS @ $35.00 Comment RG35+1 below to join the Sale   
28                                                                         Good morning Miko and OSS team   
29              RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
30               RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
31                                                                 Good Morning Miko, OSS Team  Everyone    
32                                                                                                    😱     
33                                                                                  Mrg kelvin n Lena too   
34                                                                           Good morning Miko n Team OSS   
35                                                                                       Today Wednesday    
36                                                           

We noticed that each comment has the word 'Comment' in the middle of the extracted string of comments for the column 'productPrice'. Hence, we will remove the word 'Comment'.

In [73]:
df4['productPrice'] = df4['productPrice'].replace(value='', regex=r'Comment')

In [74]:
df4.head(50)

postComment  \
0                                                                                        Gd mrg to u miko   
1                                                                                                     Oss   
2                                                                                                 Oss mrg   
3                                                                                                     Lns   
4                                                                                                    LNS    
5                                                                                                     Oss   
6                                                                         Good morning miko and OSS team    
7         BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
8                                                                                                    OSS    
9                       WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
10                                                                                                    Oss   
11              RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
12               RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
13                                                                                      Good morning OSS    
14                     BALAI THREADFIN WHOL 2.4-2.8KG/ PCS @$78.00 Comment BTW78+1 below to join the Sale   
15                                                                                               Mrg miko   
16                 BALAI THREADFIN WHOLE 5.5-6.0 KG/ PCS @$168.00 Comment BTW168+1 below to join the Sale   
17                                                                                      Mee siam mee siam   
18                                                                                                   LNS    
19                                                                                                   LNS    
20                             MACKEREL WHOLE 500-600G/ PCS @$9.90 Comment MAC99+1 below to join the Sale   
21              2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale   
22                       SALMON TROUT WHOLE 4.0-4.3 KG/ PCS @$108.00 Comment STW+1 below to join the Sale   
23                        RED SNAPPER WHOLE 1.7-1.9 KG/ PCS @$33.33 Comment RS33+1 below to join the Sale   
24                     WILD BARRAMUNDI WHOLE 3.5-3.9 KG/ PCS @ $49.90 Comment WB+1 below to join the Sale   
25                                                                                                     LS   
26                      WILD GROUPER WHOLE 2.2-2.6 KG/ PCS @$39.90 Comment WG399+1 below to join the Sale   
27                       RED GROUPER WHOLE 1.1-1.3KG / PCS @ $35.00 Comment RG35+1 below to join the Sale   
28                                                                         Good morning Miko and OSS team   
29              RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
30               RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
31                                                                 Good Morning Miko, OSS Team  Everyone    
32                                                                                                    😱     
33                                                                                  Mrg kelvin n Lena too   
34                                                                           Good morning Miko n Team OSS   
35                                                                                       Today Wednesday    
36                                                           

In [75]:
df4['productPrice'].unique()

array([0, '$39.90  EMP399+1', '$19.90  RES199+1', '$24.90  RES249+1',
       '$78.00  BTW78+1', '$168.00  BTW168+1', '$9.90  MAC99+1',
       '$108.00  STW+1', '$33.33  RS33+1', '$39.90  WG399+1',
       '$108.00  CP108+1', '$99.00  CP99+1', '$88.00  CP88+1',
       '$77.00  CP77+1', '$22.00    CP22+1', '$14.00  CP14+1',
       '$19.90  SLD+1 ', '$24.00  BSS+1', '$19.90  WGH+1', '$19.90  WGF1',
       '$19.90  WGF+1', '$13.90  CCL+1 ', '$13.90  SBY+1 ',
       '$13.90  VNL+1 ', '$13.90  MCA+1 ', '$11.11  TMP+1 ',
       '$12.90  WGH+1', '$24.90  WAK+1 ', '$58.00  RG58+1',
       '$88.00  RG88+1', '$18.00 ( PWP )  RGSS+1', '$29.90  STB+1',
       '$29.90  MC299+1', '$11.11  AMB+1', '$11.11  TMS+1',
       '$ 5.90  KBP+1', '$39.90  SL399+1 ', '$21.90  SQ+1 ',
       '$8.00  PC+1 ', '$13.90  BST+1', '$11.11  OTAK+1', '$15.90  BP+1',
       '$22.90 ( PWP )  CST229+1', '$59.90  FCF+1 ', '$11.90  KN119+1 ',
       '$11.11  BCP+1 ', '$18.00  WGT+1', '$9.90  FG+1', '$15.90  BLJ+1',
       '$11

Excluding the comments where there was no product codes as adviced by the seller, we find the number of unique products offered by the seller.

In [76]:
#number of unique products offered by the seller
int(df4['productPrice'].nunique()) - int(1)

52

In [77]:
#total number of products offered
va['numProducts'] = int(df4['productPrice'].nunique()) - int(1)

In [78]:
va

video_for  totalEmojiReaction  views  \
0  OCEANSTARLIVE/videos/263473255843186                  18    608   

   videoLength  numSellerComments  numComments  lnsQuantity  salesQuantity  \
0         4701                131         2478           12             29   

   numProducts  
0           52

**Drop irrelevant columns**

The following columns were dropped for the following reasons:

1. 'postCommentTime'
- Since a new column 'postCommentTime_final' was created to ensure that a consistent timestamp of HH:MM:SS is used consistently throughout the dataframe, and the dataframe has been thereafter reindex and sorted in accordance to time in ascending order, we dropped the original inconsistent time column 'postCommentTime' as it had varying timestamp formats of HH:MM:SS, MM:SS and M:SS.

2. 'notSeller'
- This column 'notSeller' was solely created to calculate the quantity of sales made, and the products purchased by the customer. Hence, we are able to delete it after the quantity of sales have been calculated and the identification of the products purchased by the customers have been identified.
- Notwithstanding the above, a new column 'isSeller' has been feature engineered out as well, which will tell us the same results on whether the comment is posted & written by a seller or not. 

3. 'sales'
- This column identifies the quantity of products to the unique & specific product codes. However, it includes the product codes posted by the sellers as well. Hence, this column was solely created to be multiplied against the column 'notSeller' to calculate the true quantity of sales made by customers only. Hence, we are able to delete it after the quantity of sales have been calculated.

4. 'product'
- This column 'product' was solely created to identify the products purchased by the customers. Hence, we are able to delete it after the products purchased by the customers have been identified - especially since not all products offered by the seller is being bought by the customers.

In [79]:
#drop unwanted columns
df4.drop(['postCommentTime', 'notSeller', 'sales', 'product'], axis=1, inplace=True)

In [80]:
df4.head()

postComment postCommentAuthor postCommentTime_final  isSeller  \
0  Gd mrg to u miko         Doris Pay              00:00:44         0   
1               Oss          Eve Kang              00:00:46         0   
2           Oss mrg        Samuel Goh              00:00:48         0   
3               Lns         Doris Pay              00:00:51         0   
4              LNS         Jennie Gan              00:00:55         0   

   postCommentLength  lns  salesQuantity productBought productPrice  
0                  5    0              0             0            0  
1                  1    0              0             0            0  
2                  2    0              0             0            0  
3                  1    1              0             0            0  
4                  1    1              0             0            0

### Revenue from the sale of the products

**Dummify the products bought to find the revenue**

In [81]:
#getdummies the products bought
df4 = pd.get_dummies(df4, columns = ['productBought'], drop_first = True)

In [82]:
df4.head()

postComment postCommentAuthor postCommentTime_final  isSeller  \
0  Gd mrg to u miko         Doris Pay              00:00:44         0   
1               Oss          Eve Kang              00:00:46         0   
2           Oss mrg        Samuel Goh              00:00:48         0   
3               Lns         Doris Pay              00:00:51         0   
4              LNS         Jennie Gan              00:00:55         0   

   postCommentLength  lns  salesQuantity productPrice  productBought_AMB  \
0                  5    0              0            0                  0   
1                  1    0              0            0                  0   
2                  2    0              0            0                  0   
3                  1    1              0            0                  0   
4                  1    1              0            0                  0   

   productBought_BCP  ...  productBought_RES199  productBought_RG35  \
0                  0  ...                     0                   0   
1                  0  ...                     0                   0   
2                  0  ...                     0                   0   
3                  0  ...                     0                   0   
4                  0  ...                     0                   0   

   productBought_SP  productBought_TMP  productBought_TMS  productBought_VNL  \
0                 0                  0                  0                  0   
1                 0                  0                  0                  0   
2                 0                  0                  0                  0   
3                 0                  0                  0                  0   
4                 0                  0                  0                  0   

   productBought_WGF  productBought_WGH  productBought_WGT  \
0                  0                  0                  0   
1                  0                  0                  0   
2                  0                  0                  0   
3                  0                  0                  0   
4                  0                  0                  0   

   productBought_WST299  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 28 columns]

In [83]:
# iterating the columns
for col in df4.columns:
    print(col)

postComment
postCommentAuthor
postCommentTime_final
isSeller
postCommentLength
lns
salesQuantity
productPrice
productBought_AMB
productBought_BCP
productBought_BOP
productBought_BSD
productBought_BSS
productBought_BWP
productBought_KN119
productBought_MCA
productBought_OTAK
productBought_PC
productBought_RES199
productBought_RG35
productBought_SP
productBought_TMP
productBought_TMS
productBought_VNL
productBought_WGF
productBought_WGH
productBought_WGT
productBought_WST299


Product AMB

In [84]:
df4[df4['productPrice'].str.contains('AMB', na = False, regex = False)]

postComment  \
150  AUS MELTIQUE BEEF STEAK 200G+-/ PCS @$11.11 Comment AMB+1 below to join the Sale   
152  AUS MELTIQUE BEEF STEAK 200G+-/ PCS @$11.11 Comment AMB+1 below to join the Sale   
153  AUS MELTIQUE BEEF STEAK 200G+-/ PCS @$11.11 Comment AMB+1 below to join the Sale   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
150  OceanStar Seafood              00:40:20         1                 14   
152  OceanStar Seafood              00:41:05         1                 14   
153  OceanStar Seafood              00:41:30         1                 14   

     lns  salesQuantity   productPrice  productBought_AMB  productBought_BCP  \
150    0              0  $11.11  AMB+1                  0                  0   
152    0              0  $11.11  AMB+1                  0                  0   
153    0              0  $11.11  AMB+1                  0                  0   

     ...  productBought_RES199  productBought_RG35  productBought_SP  \
150  ...                     0                   0                 0   
152  ...                     0                   0                 0   
153  ...                     0                   0                 0   

     productBought_TMP  productBought_TMS  productBought_VNL  \
150                  0                  0                  0   
152                  0                  0                  0   
153                  0                  0                  0   

     productBought_WGF  productBought_WGH  productBought_WGT  \
150                  0                  0                  0   
152                  0                  0                  0   
153                  0                  0                  0   

     productBought_WST299  
150                     0  
152                     0  
153                     0  

[3 rows x 28 columns]

In [85]:
#wrong orders are assumed to be ignored
df4['productBought_AMB'] = df4['productBought_AMB'].apply(lambda x: x*11.11)

In [86]:
df4['revenue_AMB'] = np.multiply(df4['productBought_AMB'], df4['salesQuantity'])

In [87]:
revenue_AMB = "The total revenue from the sale of the product {} is ${}". format ("AMB", format(df4['revenue_AMB'].sum(), '.2f'))
print(revenue_AMB)


The total revenue from the sale of the product AMB is $22.22


Product BCP

In [88]:
df4[df4['productPrice'].str.contains('BCP', na = False, regex = False)]

postComment  \
224  2 X BABY CHINESE POMFRET 450G+-/ PKT @$11.11 Comment BCP+1 below to join the Sale.   
232  2 X BABY CHINESE POMFRET 450G+-/ PKT @$11.11 Comment BCP+1 below to join the Sale.   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
224  OceanStar Seafood              01:02:01         1                 15   
232  OceanStar Seafood              01:03:52         1                 15   

     lns  salesQuantity    productPrice  productBought_AMB  productBought_BCP  \
224    0              0  $11.11  BCP+1                 0.0                  0   
232    0              0  $11.11  BCP+1                 0.0                  0   

     ...  productBought_RG35  productBought_SP  productBought_TMP  \
224  ...                   0                 0                  0   
232  ...                   0                 0                  0   

     productBought_TMS  productBought_VNL  productBought_WGF  \
224                  0                  0                  0   
232                  0                  0                  0   

     productBought_WGH  productBought_WGT  productBought_WST299  revenue_AMB  
224                  0                  0                     0          0.0  
232                  0                  0                     0          0.0  

[2 rows x 29 columns]

In [89]:
df4['productBought_BCP'] = df4['productBought_BCP'].apply(lambda x: x*11.11)

In [90]:
df4['revenue_BCP'] = np.multiply(df4['productBought_BCP'], df4['salesQuantity'])

In [91]:
revenue_BCP = "The total revenue from the sale of the product {} is ${}". format ("BCP", format(df4['revenue_BCP'].sum(), '.2f'))
print(revenue_BCP)

The total revenue from the sale of the product BCP is $11.11


Product BOP

In [92]:
df4[df4['productPrice'].str.contains('BOP', na = False, regex = False)]
#df4['productBought_BOP'] = df4['productBought_BOP'].apply(lambda x: x*0) #not found in seller's comments

Empty DataFrame
Columns: [postComment, postCommentAuthor, postCommentTime_final, isSeller, postCommentLength, lns, salesQuantity, productPrice, productBought_AMB, productBought_BCP, productBought_BOP, productBought_BSD, productBought_BSS, productBought_BWP, productBought_KN119, productBought_MCA, productBought_OTAK, productBought_PC, productBought_RES199, productBought_RG35, productBought_SP, productBought_TMP, productBought_TMS, productBought_VNL, productBought_WGF, productBought_WGH, productBought_WGT, productBought_WST299, revenue_AMB, revenue_BCP]
Index: []

[0 rows x 30 columns]

In [93]:
df4[df4['postComment'].str.contains('BOP', na = False, regex = False)]
#df4['productBought_BOP'] = df4['productBought_BOP'].apply(lambda x: x*0) #not found in seller's comments

Empty DataFrame
Columns: [postComment, postCommentAuthor, postCommentTime_final, isSeller, postCommentLength, lns, salesQuantity, productPrice, productBought_AMB, productBought_BCP, productBought_BOP, productBought_BSD, productBought_BSS, productBought_BWP, productBought_KN119, productBought_MCA, productBought_OTAK, productBought_PC, productBought_RES199, productBought_RG35, productBought_SP, productBought_TMP, productBought_TMS, productBought_VNL, productBought_WGF, productBought_WGH, productBought_WGT, productBought_WST299, revenue_AMB, revenue_BCP]
Index: []

[0 rows x 30 columns]

Product BSD

In [94]:
df4[df4['productPrice'].str.contains('BSD', na = False, regex = False)]
#df4['productBought_BSD'] = df4['productBought_BSD'].apply(lambda x: x*0) #not found in seller's comments

Empty DataFrame
Columns: [postComment, postCommentAuthor, postCommentTime_final, isSeller, postCommentLength, lns, salesQuantity, productPrice, productBought_AMB, productBought_BCP, productBought_BOP, productBought_BSD, productBought_BSS, productBought_BWP, productBought_KN119, productBought_MCA, productBought_OTAK, productBought_PC, productBought_RES199, productBought_RG35, productBought_SP, productBought_TMP, productBought_TMS, productBought_VNL, productBought_WGF, productBought_WGH, productBought_WGT, productBought_WST299, revenue_AMB, revenue_BCP]
Index: []

[0 rows x 30 columns]

Product BSS

In [95]:
df4[df4['productPrice'].str.contains('BSS', na = False, regex = False)]

postComment  \
57   3 X BATANG SOUP SLICED 300G/ PKT @$24.00 Comment BSS+1 below to join the Sale   
108  3 X BATANG SOUP SLICED 300G/ PKT @$24.00 Comment BSS+1 below to join the Sale   
123  3 X BATANG SOUP SLICED 300G/ PKT @$24.00 Comment BSS+1 below to join the Sale   
186  3 X BATANG SOUP SLICED 300G/ PKT @$24.00 Comment BSS+1 below to join the Sale   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
57   OceanStar Seafood              00:09:22         1                 15   
108  OceanStar Seafood              00:24:55         1                 15   
123  OceanStar Seafood              00:32:42         1                 15   
186  OceanStar Seafood              00:50:29         1                 15   

     lns  salesQuantity   productPrice  productBought_AMB  productBought_BCP  \
57     0              0  $24.00  BSS+1                0.0                0.0   
108    0              0  $24.00  BSS+1                0.0                0.0   
123    0              0  $24.00  BSS+1                0.0                0.0   
186    0              0  $24.00  BSS+1                0.0                0.0   

     ...  productBought_SP  productBought_TMP  productBought_TMS  \
57   ...                 0                  0                  0   
108  ...                 0                  0                  0   
123  ...                 0                  0                  0   
186  ...                 0                  0                  0   

     productBought_VNL  productBought_WGF  productBought_WGH  \
57                   0                  0                  0   
108                  0                  0                  0   
123                  0                  0                  0   
186                  0                  0                  0   

     productBought_WGT  productBought_WST299  revenue_AMB  revenue_BCP  
57                   0                     0          0.0          0.0  
108                  0                     0          0.0          0.0  
123                  0                     0          0.0          0.0  
186                  0                     0          0.0          0.0  

[4 rows x 30 columns]

In [96]:
df4['productBought_BSS'] = df4['productBought_BSS'].apply(lambda x: x*24.00) 

In [97]:
df4['revenue_BSS'] = np.multiply(df4['productBought_BSS'], df4['salesQuantity'])

In [98]:
revenue_BSS = "The total revenue from the sale of the product {} is ${}". format ("BSS", format(df4['revenue_BSS'].sum(), '.2f'))
print(revenue_BSS)

The total revenue from the sale of the product BSS is $48.00


Product BWP

In [99]:
df4[df4['productPrice'].str.contains('BWP', na = False, regex = False)]
#df4['productBought_BWP'] = df4['productBought_BWP'].apply(lambda x: x*0) #not found in seller's comments

Empty DataFrame
Columns: [postComment, postCommentAuthor, postCommentTime_final, isSeller, postCommentLength, lns, salesQuantity, productPrice, productBought_AMB, productBought_BCP, productBought_BOP, productBought_BSD, productBought_BSS, productBought_BWP, productBought_KN119, productBought_MCA, productBought_OTAK, productBought_PC, productBought_RES199, productBought_RG35, productBought_SP, productBought_TMP, productBought_TMS, productBought_VNL, productBought_WGF, productBought_WGH, productBought_WGT, productBought_WST299, revenue_AMB, revenue_BCP, revenue_BSS]
Index: []

[0 rows x 31 columns]

Product KN119

In [100]:
df4[df4['productPrice'].str.contains('KN119', na = False, regex = False)]

postComment  \
220  2 X KUNNING 500G/ PKT @$11.90 Comment KN119+1 below to join the Sale.   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
220  OceanStar Seafood              01:00:33         1                 13   

     lns  salesQuantity      productPrice  productBought_AMB  \
220    0              0  $11.90  KN119+1                 0.0   

     productBought_BCP  ...  productBought_TMP  productBought_TMS  \
220                0.0  ...                  0                  0   

     productBought_VNL  productBought_WGF  productBought_WGH  \
220                  0                  0                  0   

     productBought_WGT  productBought_WST299  revenue_AMB  revenue_BCP  \
220                  0                     0          0.0          0.0   

     revenue_BSS  
220          0.0  

[1 rows x 31 columns]

In [101]:
df4['productBought_KN119'] = df4['productBought_KN119'].apply(lambda x: x*11.90)

In [102]:
df4['revenue_KN119'] = np.multiply(df4['productBought_KN119'], df4['salesQuantity'])

In [103]:
revenue_KN119 = "The total revenue from the sale of the product {} is ${}". format ("KN119", format(df4['revenue_KN119'].sum(), '.2f'))
print(revenue_KN119)

The total revenue from the sale of the product KN119 is $11.90


Product MCA

In [104]:
df4[df4['productPrice'].str.contains('MCA', na = False, regex = False)]

postComment  \
70   MATCHA JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment MCA+1 below to join the Sale.   
79   MATCHA JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment MCA+1 below to join the Sale.   
169  MATCHA JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment MCA+1 below to join the Sale.   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
70   OceanStar Seafood              00:14:26         1                 16   
79   OceanStar Seafood              00:15:50         1                 16   
169  OceanStar Seafood              00:45:15         1                 16   

     lns  salesQuantity    productPrice  productBought_AMB  productBought_BCP  \
70     0              0  $13.90  MCA+1                 0.0                0.0   
79     0              0  $13.90  MCA+1                 0.0                0.0   
169    0              0  $13.90  MCA+1                 0.0                0.0   

     ...  productBought_TMS  productBought_VNL  productBought_WGF  \
70   ...                  0                  0                  0   
79   ...                  0                  0                  0   
169  ...                  0                  0                  0   

     productBought_WGH  productBought_WGT  productBought_WST299  revenue_AMB  \
70                   0                  0                     0          0.0   
79                   0                  0                     0          0.0   
169                  0                  0                     0          0.0   

     revenue_BCP  revenue_BSS  revenue_KN119  
70           0.0          0.0            0.0  
79           0.0          0.0            0.0  
169          0.0          0.0            0.0  

[3 rows x 32 columns]

In [105]:
df4['productBought_MCA'] = df4['productBought_MCA'].apply(lambda x: x*13.90)

In [106]:
df4['revenue_MCA'] = np.multiply(df4['productBought_MCA'], df4['salesQuantity'])

In [107]:
revenue_MCA = "The total revenue from the sale of the product {} is ${}". format ("MCA", format(df4['revenue_MCA'].sum(), '.2f'))
print(revenue_MCA)

The total revenue from the sale of the product MCA is $13.90


Product OTAK

In [108]:
df4[df4['productPrice'].str.contains('OTAK', na = False, regex = False)]

postComment  \
182              3 X MUAR OTAK / PKT @$11.11 Comment OTAK+1 below to join the Sale   
185  LAST SET!!! 3 X MUAR OTAK / PKT @$11.11 Comment OTAK+1 below to join the Sale   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
182  OceanStar Seafood              00:50:01         1                 14   
185  OceanStar Seafood              00:50:13         1                 16   

     lns  salesQuantity    productPrice  productBought_AMB  productBought_BCP  \
182    0              0  $11.11  OTAK+1                0.0                0.0   
185    0              0  $11.11  OTAK+1                0.0                0.0   

     ...  productBought_VNL  productBought_WGF  productBought_WGH  \
182  ...                  0                  0                  0   
185  ...                  0                  0                  0   

     productBought_WGT  productBought_WST299  revenue_AMB  revenue_BCP  \
182                  0                     0          0.0          0.0   
185                  0                     0          0.0          0.0   

     revenue_BSS  revenue_KN119  revenue_MCA  
182          0.0            0.0          0.0  
185          0.0            0.0          0.0  

[2 rows x 33 columns]

In [109]:
df4['productBought_OTAK'] = df4['productBought_OTAK'].apply(lambda x: x*11.11)

In [110]:
df4['revenue_OTAK'] = np.multiply(df4['productBought_OTAK'], df4['salesQuantity'])

In [111]:
revenue_OTAK = "The total revenue from the sale of the product {} is ${}". format ("OTAK", format(df4['revenue_OTAK'].sum(), '.2f'))
print(revenue_OTAK)

The total revenue from the sale of the product OTAK is $33.33


Product PC

In [112]:
df4[df4['productPrice'].str.contains('PC', na = False, regex = False)]

postComment  \
178  PROCESS CUTTLEFISH 500G+-/ PCS@$8.00 Comment PC+1 below to join the Sale.   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
178  OceanStar Seafood              00:48:20         1                 11   

     lns  salesQuantity  productPrice  productBought_AMB  productBought_BCP  \
178    0              0  $8.00  PC+1                 0.0                0.0   

     ...  productBought_WGF  productBought_WGH  productBought_WGT  \
178  ...                  0                  0                  0   

     productBought_WST299  revenue_AMB  revenue_BCP  revenue_BSS  \
178                     0          0.0          0.0          0.0   

     revenue_KN119  revenue_MCA  revenue_OTAK  
178            0.0          0.0           0.0  

[1 rows x 34 columns]

In [113]:
df4['productBought_PC'] = df4['productBought_PC'].apply(lambda x: x*8.00)

In [114]:
df4['revenue_PC'] = np.multiply(df4['productBought_PC'], df4['salesQuantity'])

In [115]:
revenue_PC = "The total revenue from the sale of the product {} is ${}". format ("PC", format(df4['revenue_PC'].sum(), '.2f'))
print(revenue_PC)

The total revenue from the sale of the product PC is $16.00


Product RES199

In [116]:
df4[df4['productPrice'].str.contains('RES199', na = False, regex = False)]

postComment  \
11                  RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
29                  RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
102  LAST 3 PCS!!!! RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
121                 RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
11   OceanStar Seafood              00:01:44         1                 15   
29   OceanStar Seafood              00:03:28         1                 15   
102  OceanStar Seafood              00:22:16         1                 18   
121  OceanStar Seafood              00:31:51         1                 15   

     lns  salesQuantity      productPrice  productBought_AMB  \
11     0              0  $19.90  RES199+1                0.0   
29     0              0  $19.90  RES199+1                0.0   
102    0              0  $19.90  RES199+1                0.0   
121    0              0  $19.90  RES199+1                0.0   

     productBought_BCP  ...  productBought_WGH  productBought_WGT  \
11                 0.0  ...                  0                  0   
29                 0.0  ...                  0                  0   
102                0.0  ...                  0                  0   
121                0.0  ...                  0                  0   

     productBought_WST299  revenue_AMB  revenue_BCP  revenue_BSS  \
11                      0          0.0          0.0          0.0   
29                      0          0.0          0.0          0.0   
102                     0          0.0          0.0          0.0   
121                     0          0.0          0.0          0.0   

     revenue_KN119  revenue_MCA  revenue_OTAK  revenue_PC  
11             0.0          0.0           0.0         0.0  
29             0.0          0.0           0.0         0.0  
102            0.0          0.0           0.0         0.0  
121            0.0          0.0           0.0         0.0  

[4 rows x 35 columns]

In [117]:
df4['productBought_RES199'] = df4['productBought_RES199'].apply(lambda x: x*19.90)

In [118]:
df4['revenue_RES199'] = np.multiply(df4['productBought_RES199'], df4['salesQuantity'])

In [119]:
revenue_RES199 = "The total revenue from the sale of the product {} is ${}". format ("RES199", format(df4['revenue_RES199'].sum(), '.2f'))
print(revenue_RES199)

The total revenue from the sale of the product RES199 is $19.90


Product RG35

In [120]:
df4[df4['productPrice'].str.contains('RG35', na = False, regex = False)]
#df4['productBought_RG35'] = df4['productBought_RG35'].apply(lambda x: x*0) #not found in seller's comments

Empty DataFrame
Columns: [postComment, postCommentAuthor, postCommentTime_final, isSeller, postCommentLength, lns, salesQuantity, productPrice, productBought_AMB, productBought_BCP, productBought_BOP, productBought_BSD, productBought_BSS, productBought_BWP, productBought_KN119, productBought_MCA, productBought_OTAK, productBought_PC, productBought_RES199, productBought_RG35, productBought_SP, productBought_TMP, productBought_TMS, productBought_VNL, productBought_WGF, productBought_WGH, productBought_WGT, productBought_WST299, revenue_AMB, revenue_BCP, revenue_BSS, revenue_KN119, revenue_MCA, revenue_OTAK, revenue_PC, revenue_RES199]
Index: []

[0 rows x 36 columns]

Product SP

In [121]:
df4[df4['productPrice'].str.contains('SP', na = False, regex = False)]
#df4['productBought_SP'] = df4['productBought_SP'].apply(lambda x: x*0) #not found in seller's commentsX

Empty DataFrame
Columns: [postComment, postCommentAuthor, postCommentTime_final, isSeller, postCommentLength, lns, salesQuantity, productPrice, productBought_AMB, productBought_BCP, productBought_BOP, productBought_BSD, productBought_BSS, productBought_BWP, productBought_KN119, productBought_MCA, productBought_OTAK, productBought_PC, productBought_RES199, productBought_RG35, productBought_SP, productBought_TMP, productBought_TMS, productBought_VNL, productBought_WGF, productBought_WGH, productBought_WGT, productBought_WST299, revenue_AMB, revenue_BCP, revenue_BSS, revenue_KN119, revenue_MCA, revenue_OTAK, revenue_PC, revenue_RES199]
Index: []

[0 rows x 36 columns]

Product TMP

In [122]:
df4[df4['productPrice'].str.contains('TMP', na = False, regex = False)]

postComment  \
80   2 X AUTHENTIC THAI MOO PING 5 PCS / PKT @$11.11 Comment TMP+1 below to join the Sale.   
84   2 X AUTHENTIC THAI MOO PING 5 PCS / PKT @$11.11 Comment TMP+1 below to join the Sale.   
170  2 X AUTHENTIC THAI MOO PING 5 PCS / PKT @$11.11 Comment TMP+1 below to join the Sale.   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
80   OceanStar Seafood              00:16:15         1                 18   
84   OceanStar Seafood              00:16:52         1                 18   
170  OceanStar Seafood              00:45:24         1                 18   

     lns  salesQuantity    productPrice  productBought_AMB  productBought_BCP  \
80     0              0  $11.11  TMP+1                 0.0                0.0   
84     0              0  $11.11  TMP+1                 0.0                0.0   
170    0              0  $11.11  TMP+1                 0.0                0.0   

     ...  productBought_WGT  productBought_WST299  revenue_AMB  revenue_BCP  \
80   ...                  0                     0          0.0          0.0   
84   ...                  0                     0          0.0          0.0   
170  ...                  0                     0          0.0          0.0   

     revenue_BSS  revenue_KN119  revenue_MCA  revenue_OTAK  revenue_PC  \
80           0.0            0.0          0.0           0.0         0.0   
84           0.0            0.0          0.0           0.0         0.0   
170          0.0            0.0          0.0           0.0         0.0   

     revenue_RES199  
80              0.0  
84              0.0  
170             0.0  

[3 rows x 36 columns]

In [123]:
df4['productBought_TMP'] = df4['productBought_TMP'].apply(lambda x: x*11.11) 

In [124]:
df4['revenue_TMP'] = np.multiply(df4['productBought_TMP'], df4['salesQuantity'])

In [125]:
revenue_TMP = "The total revenue from the sale of the product {} is ${}". format ("TMP", format(df4['revenue_TMP'].sum(), '.2f'))
print(revenue_TMP)

The total revenue from the sale of the product TMP is $11.11


Product TMS

In [126]:
df4[df4['productPrice'].str.contains('TMS', na = False, regex = False)]

postComment  \
159                2 X HANDMADE TRUFFLE MUSHROOM SOUP 500ML/ PKT @$11.11 Comment TMS+1 below to join the Sale   
162  LAST 2 SET!!! 2 X HANDMADE TRUFFLE MUSHROOM SOUP 500ML/ PKT @$11.11 Comment TMS+1 below to join the Sale   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
159  OceanStar Seafood              00:43:26         1                 16   
162  OceanStar Seafood              00:44:07         1                 19   

     lns  salesQuantity   productPrice  productBought_AMB  productBought_BCP  \
159    0              0  $11.11  TMS+1                0.0                0.0   
162    0              0  $11.11  TMS+1                0.0                0.0   

     ...  productBought_WST299  revenue_AMB  revenue_BCP  revenue_BSS  \
159  ...                     0          0.0          0.0          0.0   
162  ...                     0          0.0          0.0          0.0   

     revenue_KN119  revenue_MCA  revenue_OTAK  revenue_PC  revenue_RES199  \
159            0.0          0.0           0.0         0.0             0.0   
162            0.0          0.0           0.0         0.0             0.0   

     revenue_TMP  
159          0.0  
162          0.0  

[2 rows x 37 columns]

In [127]:
df4['productBought_TMS'] = df4['productBought_TMS'].apply(lambda x: x*11.11) 

In [128]:
df4['revenue_TMS'] = np.multiply(df4['productBought_TMS'], df4['salesQuantity'])

In [129]:
revenue_TMS = "The total revenue from the sale of the product {} is ${}". format ("TMS", format(df4['revenue_TMS'].sum(), '.2f'))
print(revenue_TMS)

The total revenue from the sale of the product TMS is $11.11


Product VNL

In [130]:
df4[df4['productPrice'].str.contains('VNL', na = False, regex = False)]

postComment  \
69   VANILA JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment VNL+1 below to join the Sale.   
78   VANILA JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment VNL+1 below to join the Sale.   
167  VANILA JAPAN HOKKAIDO CREPE CAKE 4 PCS/ PKT @$13.90 Comment VNL+1 below to join the Sale.   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
69   OceanStar Seafood              00:14:18         1                 16   
78   OceanStar Seafood              00:15:43         1                 16   
167  OceanStar Seafood              00:45:05         1                 16   

     lns  salesQuantity    productPrice  productBought_AMB  productBought_BCP  \
69     0              0  $13.90  VNL+1                 0.0                0.0   
78     0              0  $13.90  VNL+1                 0.0                0.0   
167    0              0  $13.90  VNL+1                 0.0                0.0   

     ...  revenue_AMB  revenue_BCP  revenue_BSS  revenue_KN119  revenue_MCA  \
69   ...          0.0          0.0          0.0            0.0          0.0   
78   ...          0.0          0.0          0.0            0.0          0.0   
167  ...          0.0          0.0          0.0            0.0          0.0   

     revenue_OTAK  revenue_PC  revenue_RES199  revenue_TMP  revenue_TMS  
69            0.0         0.0             0.0          0.0          0.0  
78            0.0         0.0             0.0          0.0          0.0  
167           0.0         0.0             0.0          0.0          0.0  

[3 rows x 38 columns]

In [131]:
df4['productBought_VNL'] = df4['productBought_VNL'].apply(lambda x: x*13.90)

In [132]:
df4['revenue_VNL'] = np.multiply(df4['productBought_VNL'], df4['salesQuantity'])

In [133]:
revenue_VNL = "The total revenue from the sale of the product {} is ${}". format ("VNL", format(df4['revenue_VNL'].sum(), '.2f'))
print(revenue_VNL)

The total revenue from the sale of the product VNL is $13.90


Product WGF

In [134]:
df4[df4['productPrice'].str.contains('WGF', na = False, regex = False)]

postComment  \
61                 2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGF1 below to join the Sale   
62                2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGF+1 below to join the Sale   
88                2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGF+1 below to join the Sale   
195  MUST GRAB!!! 2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGF+1 below to join the Sale   
233               2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGF+1 below to join the Sale   
243               2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGF+1 below to join the Sale   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
61   OceanStar Seafood              00:11:50         1                 15   
62   OceanStar Seafood              00:12:57         1                 15   
88   OceanStar Seafood              00:18:05         1                 15   
195  OceanStar Seafood              00:52:09         1                 17   
233  OceanStar Seafood              01:04:01         1                 15   
243  OceanStar Seafood              01:08:12         1                 15   

     lns  salesQuantity   productPrice  productBought_AMB  productBought_BCP  \
61     0              0   $19.90  WGF1                0.0                0.0   
62     0              0  $19.90  WGF+1                0.0                0.0   
88     0              0  $19.90  WGF+1                0.0                0.0   
195    0              0  $19.90  WGF+1                0.0                0.0   
233    0              0  $19.90  WGF+1                0.0                0.0   
243    0              0  $19.90  WGF+1                0.0                0.0   

     ...  revenue_BCP  revenue_BSS  revenue_KN119  revenue_MCA  revenue_OTAK  \
61   ...          0.0          0.0            0.0          0.0           0.0   
62   ...          0.0          0.0            0.0          0.0           0.0   
88   ...          0.0          0.0            0.0          0.0           0.0   
195  ...          0.0          0.0            0.0          0.0           0.0   
233  ...          0.0          0.0            0.0          0.0           0.0   
243  ...          0.0          0.0            0.0          0.0           0.0   

     revenue_PC  revenue_RES199  revenue_TMP  revenue_TMS  revenue_VNL  
61          0.0             0.0          0.0          0.0          0.0  
62          0.0             0.0          0.0          0.0          0.0  
88          0.0             0.0          0.0          0.0          0.0  
195         0.0             0.0          0.0          0.0          0.0  
233         0.0             0.0          0.0          0.0          0.0  
243         0.0             0.0          0.0          0.0          0.0  

[6 rows x 39 columns]

In [135]:
df4['productBought_WGF'] = df4['productBought_WGF'].apply(lambda x: x*19.90)

In [136]:
df4['revenue_WGF'] = np.multiply(df4['productBought_WGF'], df4['salesQuantity'])

In [137]:
revenue_WGF = "The total revenue from the sale of the product {} is ${}". format ("WGF", format(df4['revenue_WGF'].sum(), '.2f'))
print(revenue_WGF)

The total revenue from the sale of the product WGF is $39.80


Product WGH

In [138]:
df4[df4['productPrice'].str.contains('WGH', na = False, regex = False)]

postComment  \
58   2 X WILD GROUPER FILLET 300-350G/ PCS @$19.90 Comment WGH+1 below to join the Sale   
101      WILD GROUPER HEAD 1.0-1.3 KG/ PCS @$12.90 Comment WGH+1 below to join the Sale   
237      WILD GROUPER HEAD 1.0-1.3 KG/ PCS @$12.90 Comment WGH+1 below to join the Sale   
242      WILD GROUPER HEAD 1.0-1.3 KG/ PCS @$12.90 Comment WGH+1 below to join the Sale   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
58   OceanStar Seafood              00:10:30         1                 15   
101  OceanStar Seafood              00:21:47         1                 14   
237  OceanStar Seafood              01:06:15         1                 14   
242  OceanStar Seafood              01:08:01         1                 14   

     lns  salesQuantity   productPrice  productBought_AMB  productBought_BCP  \
58     0              0  $19.90  WGH+1                0.0                0.0   
101    0              0  $12.90  WGH+1                0.0                0.0   
237    0              0  $12.90  WGH+1                0.0                0.0   
242    0              0  $12.90  WGH+1                0.0                0.0   

     ...  revenue_BSS  revenue_KN119  revenue_MCA  revenue_OTAK  revenue_PC  \
58   ...          0.0            0.0          0.0           0.0         0.0   
101  ...          0.0            0.0          0.0           0.0         0.0   
237  ...          0.0            0.0          0.0           0.0         0.0   
242  ...          0.0            0.0          0.0           0.0         0.0   

     revenue_RES199  revenue_TMP  revenue_TMS  revenue_VNL  revenue_WGF  
58              0.0          0.0          0.0          0.0          0.0  
101             0.0          0.0          0.0          0.0          0.0  
237             0.0          0.0          0.0          0.0          0.0  
242             0.0          0.0          0.0          0.0          0.0  

[4 rows x 40 columns]

For the product of product code WGH+1, we noticed that the seller had initially proposed the sale of the product to be at \\$19.90. However, 10 mins later onwards, every comment with regards to this particular product has been advised to be of a lower price of \\$12.90. This could possibly be due to an initial typo error in the price being advised to the customers for the product of product code WGH+1.

Hence, we assume the latest price of the product to be the price of the particular product. 

In [139]:
#if there are inconsistent prices, the latest price is assumed. For example, WGH+1.
df4['productBought_WGH'] = df4['productBought_WGH'].apply(lambda x: x*12.90)

In [140]:
df4['revenue_WGH'] = np.multiply(df4['productBought_WGH'], df4['salesQuantity'])

In [141]:
revenue_WGH = "The total revenue from the sale of the product {} is ${}". format ("WGH", format(df4['revenue_WGH'].sum(), '.2f'))
print(revenue_WGH)

The total revenue from the sale of the product WGH is $12.90


Product WGT

In [142]:
df4[df4['productPrice'].str.contains('WGT', na = False, regex = False)]

postComment  \
236  WILD GROUPER TAIL PORTION 600-700G/ PCS @$18.00 Comment WGT+1 below to join the Sale   

     postCommentAuthor postCommentTime_final  isSeller  postCommentLength  \
236  OceanStar Seafood              01:05:05         1                 14   

     lns  salesQuantity   productPrice  productBought_AMB  productBought_BCP  \
236    0              0  $18.00  WGT+1                0.0                0.0   

     ...  revenue_KN119  revenue_MCA  revenue_OTAK  revenue_PC  \
236  ...            0.0          0.0           0.0         0.0   

     revenue_RES199  revenue_TMP  revenue_TMS  revenue_VNL  revenue_WGF  \
236             0.0          0.0          0.0          0.0          0.0   

     revenue_WGH  
236          0.0  

[1 rows x 41 columns]

In [143]:
df4['productBought_WGT'] = df4['productBought_WGT'].apply(lambda x: x*18.00)

In [144]:
df4['revenue_WGT'] = np.multiply(df4['productBought_WGT'], df4['salesQuantity'])

In [145]:
revenue_WGT = "The total revenue from the sale of the product {} is ${}". format ("WGT", format(df4['revenue_WGT'].sum(), '.2f'))
print(revenue_WGT)

The total revenue from the sale of the product WGT is $18.00


Product WST299

In [146]:
df4[df4['productPrice'].str.contains('WST299', na = False, regex = False)]
#df4['productBought_WST299'] = df4['productBought_WST299'].apply(lambda x: x*0) #not found in seller's comments

Empty DataFrame
Columns: [postComment, postCommentAuthor, postCommentTime_final, isSeller, postCommentLength, lns, salesQuantity, productPrice, productBought_AMB, productBought_BCP, productBought_BOP, productBought_BSD, productBought_BSS, productBought_BWP, productBought_KN119, productBought_MCA, productBought_OTAK, productBought_PC, productBought_RES199, productBought_RG35, productBought_SP, productBought_TMP, productBought_TMS, productBought_VNL, productBought_WGF, productBought_WGH, productBought_WGT, productBought_WST299, revenue_AMB, revenue_BCP, revenue_BSS, revenue_KN119, revenue_MCA, revenue_OTAK, revenue_PC, revenue_RES199, revenue_TMP, revenue_TMS, revenue_VNL, revenue_WGF, revenue_WGH, revenue_WGT]
Index: []

[0 rows x 42 columns]

In [147]:
# iterating the columns
for col in df4.columns:
    print(col)

postComment
postCommentAuthor
postCommentTime_final
isSeller
postCommentLength
lns
salesQuantity
productPrice
productBought_AMB
productBought_BCP
productBought_BOP
productBought_BSD
productBought_BSS
productBought_BWP
productBought_KN119
productBought_MCA
productBought_OTAK
productBought_PC
productBought_RES199
productBought_RG35
productBought_SP
productBought_TMP
productBought_TMS
productBought_VNL
productBought_WGF
productBought_WGH
productBought_WGT
productBought_WST299
revenue_AMB
revenue_BCP
revenue_BSS
revenue_KN119
revenue_MCA
revenue_OTAK
revenue_PC
revenue_RES199
revenue_TMP
revenue_TMS
revenue_VNL
revenue_WGF
revenue_WGH
revenue_WGT


**Sum of total revenue from the video**

In [148]:
#total revenue from the video
total_revenue = df4.loc[:, 'revenue_AMB': 'revenue_WGT'].values.sum()

#round the total revenue to 2 decimals places
total_revenue_rounded = format(total_revenue, '.2f')

print(f"The total revenue for the sale of products for the video is ${total_revenue_rounded}")


The total revenue for the sale of products for the video is $283.18


In [149]:
va['totalRevenue'] = total_revenue_rounded
va

video_for  totalEmojiReaction  views  \
0  OCEANSTARLIVE/videos/263473255843186                  18    608   

   videoLength  numSellerComments  numComments  lnsQuantity  salesQuantity  \
0         4701                131         2478           12             29   

   numProducts totalRevenue  
0           52       283.18

**New Column for the total revenue at that comment**

In [150]:
#https://stackoverflow.com/questions/42063716/pandas-sum-up-multiple-columns-into-one-column-without-last-column
df4['revenue'] = df4.loc[:, 'revenue_AMB': 'revenue_WGT'].sum(axis=1)
df4

postComment  \
0                                                                                                  Gd mrg to u miko   
1                                                                                                               Oss   
2                                                                                                           Oss mrg   
3                                                                                                               Lns   
4                                                                                                              LNS    
5                                                                                                               Oss   
6                                                                                   Good morning miko and OSS team    
7                   BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
8                                                                                                              OSS    
9                                 WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
10                                                                                                              Oss   
11                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
12                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
13                                                                                                Good morning OSS    
14                               BALAI THREADFIN WHOL 2.4-2.8KG/ PCS @$78.00 Comment BTW78+1 below to join the Sale   
15                                                                                                         Mrg miko   
16                           BALAI THREADFIN WHOLE 5.5-6.0 KG/ PCS @$168.00 Comment BTW168+1 below to join the Sale   
17                                                                                                Mee siam mee siam   
18                                                                                                             LNS    
19                                                                                                             LNS    
20                                       MACKEREL WHOLE 500-600G/ PCS @$9.90 Comment MAC99+1 below to join the Sale   
21                        2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale   
22                                 SALMON TROUT WHOLE 4.0-4.3 KG/ PCS @$108.00 Comment STW+1 below to join the Sale   
23                                  RED SNAPPER WHOLE 1.7-1.9 KG/ PCS @$33.33 Comment RS33+1 below to join the Sale   
24                               WILD BARRAMUNDI WHOLE 3.5-3.9 KG/ PCS @ $49.90 Comment WB+1 below to join the Sale   
25                                                                                                               LS   
26                                WILD GROUPER WHOLE 2.2-2.6 KG/ PCS @$39.90 Comment WG399+1 below to join the Sale   
27                                 RED GROUPER WHOLE 1.1-1.3KG / PCS @ $35.00 Comment RG35+1 below to join the Sale   
28                                                                                   Good morning Miko and OSS team   
29                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
30                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
31                                                                           Good Morning Miko, OSS Team  Everyone    
32                                                                                                              😱     
33                                                        

In [151]:
#https://www.geeksforgeeks.org/how-to-move-a-column-to-first-position-in-pandas-dataframe/
#shift the revenue column to be the 8th column, i.e at position 7
eighth_column = df4.pop('revenue')

# insert column using insert(position,column_name,ninth_column) function
df4.insert(7, 'revenue', eighth_column)
df4

postComment  \
0                                                                                                  Gd mrg to u miko   
1                                                                                                               Oss   
2                                                                                                           Oss mrg   
3                                                                                                               Lns   
4                                                                                                              LNS    
5                                                                                                               Oss   
6                                                                                   Good morning miko and OSS team    
7                   BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
8                                                                                                              OSS    
9                                 WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
10                                                                                                              Oss   
11                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
12                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
13                                                                                                Good morning OSS    
14                               BALAI THREADFIN WHOL 2.4-2.8KG/ PCS @$78.00 Comment BTW78+1 below to join the Sale   
15                                                                                                         Mrg miko   
16                           BALAI THREADFIN WHOLE 5.5-6.0 KG/ PCS @$168.00 Comment BTW168+1 below to join the Sale   
17                                                                                                Mee siam mee siam   
18                                                                                                             LNS    
19                                                                                                             LNS    
20                                       MACKEREL WHOLE 500-600G/ PCS @$9.90 Comment MAC99+1 below to join the Sale   
21                        2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale   
22                                 SALMON TROUT WHOLE 4.0-4.3 KG/ PCS @$108.00 Comment STW+1 below to join the Sale   
23                                  RED SNAPPER WHOLE 1.7-1.9 KG/ PCS @$33.33 Comment RS33+1 below to join the Sale   
24                               WILD BARRAMUNDI WHOLE 3.5-3.9 KG/ PCS @ $49.90 Comment WB+1 below to join the Sale   
25                                                                                                               LS   
26                                WILD GROUPER WHOLE 2.2-2.6 KG/ PCS @$39.90 Comment WG399+1 below to join the Sale   
27                                 RED GROUPER WHOLE 1.1-1.3KG / PCS @ $35.00 Comment RG35+1 below to join the Sale   
28                                                                                   Good morning Miko and OSS team   
29                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
30                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
31                                                                           Good Morning Miko, OSS Team  Everyone    
32                                                                                                              😱     
33                                                        

After the revenue of the sales have been calculated, all the dummified product columns and the column 'productPrice' will be dropped as they are no longer required to be checked against to identify the price of the product.

In [152]:
df4 = df4.loc[: ,'postComment':'revenue']
df4

postComment  \
0                                                                                                  Gd mrg to u miko   
1                                                                                                               Oss   
2                                                                                                           Oss mrg   
3                                                                                                               Lns   
4                                                                                                              LNS    
5                                                                                                               Oss   
6                                                                                   Good morning miko and OSS team    
7                   BIG FISHES!!! WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
8                                                                                                              OSS    
9                                 WILD CAUGHT EMPURAU 600-900G/ PCS @$39.90 Comment EMP399+1 below to join the Sale   
10                                                                                                              Oss   
11                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
12                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
13                                                                                                Good morning OSS    
14                               BALAI THREADFIN WHOL 2.4-2.8KG/ PCS @$78.00 Comment BTW78+1 below to join the Sale   
15                                                                                                         Mrg miko   
16                           BALAI THREADFIN WHOLE 5.5-6.0 KG/ PCS @$168.00 Comment BTW168+1 below to join the Sale   
17                                                                                                Mee siam mee siam   
18                                                                                                             LNS    
19                                                                                                             LNS    
20                                       MACKEREL WHOLE 500-600G/ PCS @$9.90 Comment MAC99+1 below to join the Sale   
21                        2 X COD TAIL PORTION 1.0-1.2 KG/ PCS ( ST) @ $111.11 Comment PCT+1 below to join the Sale   
22                                 SALMON TROUT WHOLE 4.0-4.3 KG/ PCS @$108.00 Comment STW+1 below to join the Sale   
23                                  RED SNAPPER WHOLE 1.7-1.9 KG/ PCS @$33.33 Comment RS33+1 below to join the Sale   
24                               WILD BARRAMUNDI WHOLE 3.5-3.9 KG/ PCS @ $49.90 Comment WB+1 below to join the Sale   
25                                                                                                               LS   
26                                WILD GROUPER WHOLE 2.2-2.6 KG/ PCS @$39.90 Comment WG399+1 below to join the Sale   
27                                 RED GROUPER WHOLE 1.1-1.3KG / PCS @ $35.00 Comment RG35+1 below to join the Sale   
28                                                                                   Good morning Miko and OSS team   
29                        RED EMPEROR SNAPPER WHOLE 1.1-1.4 KG/ PCS @$19.90 Comment RES199+1 below to join the Sale   
30                         RED EMPEROR SNAPPER WHOLE1.6-1.8 KG/ PCS @$24.90 Comment RES249+1 below to join the Sale   
31                                                                           Good Morning Miko, OSS Team  Everyone    
32                                                                                                              😱     
33                                                        

**New Column to identify the frequency of the seller's comments in the video**

In [153]:
#frequency of seller's comments
va['frequencySeller']= np.divide(va['videoLength'].iloc[0],va['numSellerComments'])
#seller's comment appears on average of every 35 seconds

In [154]:
va

video_for  totalEmojiReaction  views  \
0  OCEANSTARLIVE/videos/263473255843186                  18    608   

   videoLength  numSellerComments  numComments  lnsQuantity  salesQuantity  \
0         4701                131         2478           12             29   

   numProducts totalRevenue  frequencySeller  
0           52       283.18        35.885496

**New Column to identify the seller**

In [155]:
df4['seller'] = 'OCEANSTARLIVE'

In [156]:
df4.head()

postComment postCommentAuthor postCommentTime_final  isSeller  \
0  Gd mrg to u miko         Doris Pay              00:00:44         0   
1               Oss          Eve Kang              00:00:46         0   
2           Oss mrg        Samuel Goh              00:00:48         0   
3               Lns         Doris Pay              00:00:51         0   
4              LNS         Jennie Gan              00:00:55         0   

   postCommentLength  lns  salesQuantity  revenue         seller  
0                  5    0              0      0.0  OCEANSTARLIVE  
1                  1    0              0      0.0  OCEANSTARLIVE  
2                  2    0              0      0.0  OCEANSTARLIVE  
3                  1    1              0      0.0  OCEANSTARLIVE  
4                  1    1              0      0.0  OCEANSTARLIVE

**New Column for the Average Compound Score from Sentiment Analysis on raw & uncleaned comments for video**

In [157]:
# Instantiate Sentiment Intensity Analyzer
sent = SentimentIntensityAnalyzer()

In [158]:
df4['sentiment_score'] = df4['postComment'].apply(sent.polarity_scores)
df4['compound'] = [sent.polarity_scores(x)['compound'] for x in df4['postComment']]
df4.head()

postComment postCommentAuthor postCommentTime_final  isSeller  \
0  Gd mrg to u miko         Doris Pay              00:00:44         0   
1               Oss          Eve Kang              00:00:46         0   
2           Oss mrg        Samuel Goh              00:00:48         0   
3               Lns         Doris Pay              00:00:51         0   
4              LNS         Jennie Gan              00:00:55         0   

   postCommentLength  lns  salesQuantity  revenue         seller  \
0                  5    0              0      0.0  OCEANSTARLIVE   
1                  1    0              0      0.0  OCEANSTARLIVE   
2                  2    0              0      0.0  OCEANSTARLIVE   
3                  1    1              0      0.0  OCEANSTARLIVE   
4                  1    1              0      0.0  OCEANSTARLIVE   

                                         sentiment_score  compound  
0  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}       0.0  
1  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}       0.0  
2  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}       0.0  
3  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}       0.0  
4  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}       0.0

In [159]:
#average compound scores for the video
#df4.shape[0] calculates the total number of rows in the dataframe
va['averageCompound']= (df4['compound'].sum())/(df4['compound'].sum())/df4.shape[0]
va

video_for  totalEmojiReaction  views  \
0  OCEANSTARLIVE/videos/263473255843186                  18    608   

   videoLength  numSellerComments  numComments  lnsQuantity  salesQuantity  \
0         4701                131         2478           12             29   

   numProducts totalRevenue  frequencySeller  averageCompound  
0           52       283.18        35.885496         0.003584

In [160]:
#drop the columns with regarding to the sentiment analysis on the raw & uncleaned comments
#as we will perform sentiment analysis at the comment level on processed comments
df4 = df4.loc[: ,'postComment':'seller']
df4.head()

postComment postCommentAuthor postCommentTime_final  isSeller  \
0  Gd mrg to u miko         Doris Pay              00:00:44         0   
1               Oss          Eve Kang              00:00:46         0   
2           Oss mrg        Samuel Goh              00:00:48         0   
3               Lns         Doris Pay              00:00:51         0   
4              LNS         Jennie Gan              00:00:55         0   

   postCommentLength  lns  salesQuantity  revenue         seller  
0                  5    0              0      0.0  OCEANSTARLIVE  
1                  1    0              0      0.0  OCEANSTARLIVE  
2                  2    0              0      0.0  OCEANSTARLIVE  
3                  1    1              0      0.0  OCEANSTARLIVE  
4                  1    1              0      0.0  OCEANSTARLIVE

### Saving the cleaned dataframes

In [161]:
# export to csv - change the name of the data file for each video
va.to_csv('../../data/cleaned_data/cleaned_va_OCEANSTARLIVE_263473255843186.csv', index=False)

In [162]:
#check for nulls
#displaying only the columns with nulls and their sum
df4[df4.columns[df4.isnull().any()]].isnull().sum()

Series([], dtype: float64)

In [163]:
# export to csv - change the name of the data file for each video
df4.to_csv('../../data/cleaned_data/cleaned_OCEANSTARLIVE_263473255843186.csv', index=False)